In [8]:
from core.config import ConfigManager
from astropy.coordinates import SkyCoord
from pathlib import Path
import os
from core.logger import PipelineLogger
from core.directory_manager import DirectoryManager
from core.hdf5_handler import HDF5Handler
from core.map_tools import MapGenerator

In [9]:
config = ConfigManager('config.yaml')
method = config.get('fitting_procedure')
coordsys = config.get('coordinates.coord_sys', 'equatorial')
output_path = config.get('fitting.output_dir')
output_dir_name = config.get('fitting.fit_name')

# Test logger
logger = PipelineLogger('./logs')
logger.info("Pipeline test")

directory_manager = DirectoryManager(output_path, output_dir_name, logger=logger)
directory_manager.create_structure()

ra = config.get('coordinates.ra')
dec = config.get('coordinates.dec')
if ra is None or dec is None:
    l = config.get('coordinates.l')
    b = config.get('coordinates.b')
    if l is None or b is None:
        raise ValueError("Config must set either (ra, dec) or (l, b) for the ROI center")
    c = SkyCoord(l, b, frame='galactic', unit='deg')
    ra = float(c.icrs.ra.deg)
    dec = float(c.icrs.dec.deg)
    logger.info(f"Converted galactic coordinates (l={l}, b={b}) to equatorial (RA={ra}, Dec={dec})")
    config.set('coordinates.ra', ra)
    config.set('coordinates.dec', dec)


print(f"Fitting method: {method}")
print(f"Coordinate system: {coordsys}")
print(f"RA: {ra}")
print(f"Dec: {dec}")
print(f"Output path: {output_path}")
print(f"Output directory name: {output_dir_name}")

2026-08-24 10:17:51 - Pipeline - INFO - Pipeline logger initialized
2026-08-24 10:17:51 - Pipeline - INFO - Log level: INFO
2026-08-24 10:17:51 - Pipeline - INFO - Pipeline log: logs/pipeline_20260824_101751.log
2026-08-24 10:17:51 - Pipeline - INFO - Full log: logs/full_log_20260824_101751.log
2026-08-24 10:17:51 - Pipeline - INFO - Pipeline test
2026-08-24 10:17:51 - Pipeline - INFO - Initialized DirectoryManager at /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1
2026-08-24 10:17:51 - Pipeline - INFO - Directory structure created at /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1

Fitting method: Drips
Coordinate system: C
RA: 83
Dec: 22
Output path: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/
Output directory name: Run1

In [10]:
###Drips 
step_dir = directory_manager.get_step_results_dir('Step0-Allpoint-sources')

In [11]:
def _build_significance_map():
        """Build the significance map from count maps if coordinates.create_sig_map."""
        if not config.get('coordinates.create_sig_map', False):
            return None
        sig_map_path_cfe = config.get('coordinates.sig_map_path')
        if sig_map_path_cfe:
            sig_map_path = Path(sig_map_path_cfe)
        else:
            sig_map_path = directory_manager.get_datamap_dir() / "significance_map.fits"
            logger.info(f"Significance map already exists at {sig_map_path}, skipping generation")
            config.set("coordinates.sig_map_path", str(sig_map_path))
        if sig_map_path.exists():
            logger.info(f"Significance map already exists at {sig_map_path}, skipping generation")
            return sig_map_path
        
        # checkpoint.save_step('build_significance_map', 0, 'running', {})
        count_map_dir = config.get('coordinates.count_map_dir')
        image_bins = config.get('coordinates.image_bins')
        detector_response = config.get('coordinates.detector_response')

        fits_mapping = MapGenerator.find_fits_files_by_bins(count_map_dir, image_bins, logger=logger)
        if not fits_mapping:
            checkpoint.save_step('build_significance_map', 0, 'failed', {'error': 'no count-map FITS files found'})
            raise RuntimeError(f"No count-map FITS files found in {count_map_dir} for bins {image_bins}")
        ra = config.get('coordinates.ra')
        dec = config.get('coordinates.dec')
        if ra is None or dec is None:
            l = config.get('coordinates.l')
            b = config.get('coordinates.b')
            skycoord = SkyCoord(l, b, frame='galactic', unit='deg')
            ra = skycoord.icrs.ra.deg
            dec = skycoord.icrs.dec.deg
            logger.info(f"Converted galactic coordinates (l={l}, b={b}) to equatorial (RA={ra}, Dec={dec})")
            config.set('coordinates.ra', ra)
            config.set('coordinates.dec', dec) 
        
        output_path = MapGenerator.create_healpix_map(
            input_fits_files=list(fits_mapping.values()),
            energy_bins=list(fits_mapping.keys()),
            detector_response=detector_response,
            ra_center=float(config.get('coordinates.ra')),
            dec_center=float(config.get('coordinates.dec')),
            roi_x=float(10.0),
            roi_y=float(10.0),
            output_file=str(sig_map_path),
            logger=logger,
            pixi_manifest_path=config.get('alps.pixi_aerie_folder'),
        )

In [12]:
_build_significance_map()

2026-08-24 10:17:51 - Pipeline - INFO - Significance map already exists at /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/DataMapDir/significance_map.fits, skipping generation
2026-08-24 10:17:51 - Pipeline - INFO - Searching for FITS files in /Users/rishi/Documents/Analysis/data/fhitcountmaps/
2026-08-24 10:17:51 - Pipeline - INFO - Looking for bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']
2026-08-24 10:17:51 - Pipeline - INFO - Found 9/9 energy bins
2026-08-24 10:17:51 - Pipeline - INFO - Creating HEALPix map from 9 FITS files
2026-08-24 10:17:51 - Pipeline - INFO - Energy bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']
2026-08-24 10:17:51 - Pipeline - INFO - Executing HealpixSigFluxMap command:
2026-08-24 10:18:34 - Pipeline - INFO - HEALPix map created successfully: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/DataMapDir/significance_map.fits

WARNING: version mismatch between CFITSIO header (v4.006002) and linked library (v4.0602).

WARNING [CommandLineConfigurator.cc, enableFPExceptions:213]: Floating point exceptions will not be enabled on thisarchitecture
INFO [HealpixSigFluxMap.cc, main:205]: Bin B2C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B3C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B4C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B5C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B6C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B7C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B8C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B9C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B10C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:216]: Opening maps...
INFO [HealpixSigFluxMap.cc, main:274]: Processing detector response...
INFO [TF1PointSource.cc, describe:140]:
TF1 Point Source:
  Name:          ps
  R.A. (J2000):  80 deg
  Dec. (J2000):  20 deg
INFO [Func1.h, PrintOut:94]:
Function: [0]*pow(x/[3],-[1])*exp(-x/[2]):
  (Par 0) Norm: 1 +/- 0.5
  (Par 1) Index: 2.6 +/- 0.1
  (Par 2) CutOff: 1.79769e+308 +/- 8.98847e+307
  (Par 3) Pivot: 7 +/- 0
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root

In [18]:
%load_ext autoreload
%autoreload 2
from drips_seeder import DRIPSSeeder
config = ConfigManager('config.yaml')
seeder = DRIPSSeeder(config, logger, directory_manager, step_path=str(step_dir))
drip_model_path = seeder.run()

2026-08-24 10:33:59 - Pipeline - INFO - Using significance map created: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/DataMapDir/significance_map.fits
2026-08-24 10:33:59 - Pipeline - INFO - Using galactic coordinates from config: (l=184.25262566216776, b=-6.287179548958748)
2026-08-24 10:33:59 - Pipeline - INFO - ROI size: 4.0° x 4.0°
2026-08-24 10:33:59 - Pipeline - INFO - Output directory for seeding: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources
2026-08-24 10:33:59 - Pipeline - INFO - Running seed model search in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources
2026-08-24 10:33:59 - Pipeline - INFO - Loading HAWC data from /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/DataMapDir/significance_map.fits

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
ROI center in Galactic Coordintes = 184.25262566216776, -6.287179548958748
Loading Galactic Map
Fits File loaded
Degrees per pixel: 0.005555555555555556
  Map shape  : 1440 × 1440  |  pixel size: 0.0056°
  Sig range  : [-1637500000000000486439473119232.00, 311.27]
Peak intensity pixel location: (np.int64(810), np.int64(666))
Peak intensity sky location: <SkyCoord (Galactic): (l, b) in deg
    (184.54857275, -5.78153949)>
Peak intensity value: 311.26931404478034
Plotting contours [7, 9, 12, 13, 14, 15]
  Max significance 311.27sigma exceeds threshold 5.0sigma — proceeding with analysis.
  Image softly floored to -5sigma

Processing radius 0.25°:   0%|          | 0/4 [00:00<?, ?it/s]

Number of pixels corresponding to 0.25 smear radius = 45.00
Estimated background RMS: 0.0025402302952843877

Processing radius 0.30°:  25%|██▌       | 1/4 [00:06<00:18,  6.02s/it]

Raw blobs — point source: 1, extended: 1
Sources after 5$\sigma$ filtering: 2
Number of pixels corresponding to 0.30 smear radius = 54.00
Estimated background RMS: 0.0027455169980719445

Processing radius 0.40°:  50%|█████     | 2/4 [00:12<00:12,  6.08s/it]

Raw blobs — point source: 1, extended: 1
Sources after 5$\sigma$ filtering: 2
Number of pixels corresponding to 0.40 smear radius = 72.00
Estimated background RMS: 0.0030506987878638698

Processing radius 0.50°:  75%|███████▌  | 3/4 [00:18<00:06,  6.10s/it]

Raw blobs — point source: 2, extended: 1
Sources after 5$\sigma$ filtering: 3
Number of pixels corresponding to 0.50 smear radius = 90.00
Estimated background RMS: 0.0033270481966397704

Raw blobs — point source: 3, extended: 1
Sources after 5$\sigma$ filtering: 3
  PS  after all cuts:    2
  EXT after all cuts:    1
Plotting contours [7, 9, 12, 13, 14, 15]

Intensity Fraction of pixels greater than 5 sigma detection threshold = 100.0%
Larger blob coord = (np.float64(184.54857275384114), np.float64(-5.781539491143903))
  No smaller blobs overlapping larger blob — tagging as EXT
  Very close PS blob at (x=664, y=809, r=27.00 pixels) with sep=0.012° — tagging as EXT
PS flagged: 1
  Kept   — PS: 2  EXT: 0
  Removed— PS: 0  EXT: 1
  PS dedup: 2 → 2 kept, 0 removed
Final — PS kept: 2  EXT kept: 0
        PS removed: 0  EXT removed: 1
  Kept   — PS: 2  EXT: 0
  Removed— PS: 0  EXT: 1

2026-08-24 10:34:28 - Pipeline - INFO - Found 2 sources, 2 within original ROI
2026-08-24 10:34:28 - Pipeline - INFO - Results saved to: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources/filtered_sources.yaml
2026-08-24 10:34:28 - Pipeline - INFO - Results saved to: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources/filtered_sources.yaml

Converting blob at (x=664.0, y=809.0, r=27.00 pixels) to coord (RA=83.632°, Dec=22.011°) with radius 0.15°
Converting blob at (x=702.0, y=1250.0, r=27.00 pixels) to coord (RA=85.764°, Dec=23.488°) with radius 0.15°
Plotting contours [7, 9, 12, 13, 14, 15]
Model saved to: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources/curModel.model

In [19]:
%load_ext autoreload
%autoreload 2
import importlib
import source_fitter
import astromodels
importlib.reload(source_fitter)
logger.info('Starting source_fitter (DRIPS-seeded in-process fit)')
config = ConfigManager('config.yaml')
fit_output = source_fitter.run_joint_fit(drip_model_path, config, logger, directory_manager)

2026-08-24 10:34:32 - Pipeline - INFO - Starting source_fitter (DRIPS-seeded in-process fit)
2026-08-24 10:34:32 - Pipeline - INFO - Running joint fit on DRIPS seed model (/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources/curModel.model) in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit
2026-08-24 10:34:32 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit  with compute_err=False, compute_TS=True, make_maps=True
2026-08-24 10:34:32 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 10:34:32 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 10:34:32 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources/curModel.model
2026-08-24 10:34:32 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 10:34:32 - Pipeline - INFO - ROI center: 83, 22
2026-08-24 10:34:32 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
['Source0', 'Source1']
83 22 15
Center of ROI  RA: 83.0000 Dec: 22.0000 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source0          83.6319    22.0111   0.586 degrees
Source1          85.7644    23.4881   2.952 degrees

2026-08-24 10:34:47 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  200054.62190030178
TOTAL =  200054.62
CURRENT =  200054.62190030178
CURRENT =  200054.62

Best fit values:

,result,unit
parameter,,
Source0.position.ra,(8.363362089771368 +/- 0) x 10,deg
Source0.position.dec,(2.2011913693774288 +/- 0) x 10,deg
Source0.spectrum.main.Powerlaw.K,(9.136097272756285 +/- 0) x 10^-23,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.588054625546234 +/- 0,
Source1.position.ra,(8.571565468678614 +/- 0) x 10,deg
Source1.position.dec,(2.3448009583765788 +/- 0) x 10,deg
Source1.spectrum.main.Powerlaw.K,(1.187846947147763 +/- 0) x 10^-24,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.3849917725734113 +/- 0,

Correlation matrix:

nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC        200054.6219
total       200054.6219

Values of statistical measures:

     statistical measures
AIC         400125.243869
BIC         400225.713305

Best fit values:

,result,unit
parameter,,
Source0.position.ra,(8.363362089771368 +/- 0) x 10,deg
Source0.position.dec,(2.2011913693774288 +/- 0) x 10,deg
Source0.spectrum.main.Powerlaw.K,(9.136097272756285 +/- 0) x 10^-23,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.588054625546234 +/- 0,
Source1.position.ra,(8.571565468678614 +/- 0) x 10,deg
Source1.position.dec,(2.3448009583765788 +/- 0) x 10,deg
Source1.spectrum.main.Powerlaw.K,(1.187846947147763 +/- 0) x 10^-24,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.3849917725734113 +/- 0,

Correlation matrix:

nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC        200054.6219
total       200054.6219

Values of statistical measures:

     statistical measures
AIC         400125.243869
BIC         400225.713305

2026-08-24 10:35:40 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/likelihoodResults.fits
2026-08-24 10:35:40 - Pipeline - INFO - Calculating TS for all sources in the model
2026-08-24 10:35:40 - Pipeline - INFO - Computing TS for source: Source0

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  249188.88137048323
TOTAL =  249188.88
CURRENT =  249188.88137048323
CURRENT =  249188.88

2026-08-24 10:35:44 - Pipeline - INFO - TS for source Source0: 98268.5189403629
2026-08-24 10:35:44 - Pipeline - INFO - Computing TS for source: Source1
2026-08-24 10:35:47 - Pipeline - INFO - Error computing TS for source Source1:
2026-08-24 10:35:47 - Pipeline - INFO - Saving HAL output maps
2026-08-24 10:35:47 - Pipeline - INFO - SAVE A BIG MAP

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  200082.3978747035
TOTAL =  200082.4
CURRENT =  200082.3874893636
CURRENT =  200082.39

2026-08-24 10:36:17 - Pipeline - INFO - Writing model map...
2026-08-24 10:36:17 - Pipeline - INFO - Fit Step1-JointFit: -logL=200054.622, AIC=400125.244 (1.76 min)
2026-08-24 10:36:17 - Pipeline - INFO - Converting HDF5 to FITS: residual_fit.hd5
2026-08-24 10:36:23 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB2C0.fits.gz
2026-08-24 10:36:28 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB3C0.fits.gz
2026-08-24 10:36:32 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB4C0.fits.gz
2026-08-24 10:36:37 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB5C0.fits.gz
2026-08-24 10:36:41 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB6C0.fits.gz
2026-08-24 10:36:44 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB7C0.fits.gz
2026-08-24 10:36:47 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB8C0.fits.gz
2026-08-24 10:36:50 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB9C0.fits.gz
2026-08-24 10:36:52 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB10C0.fits.gz
2026-08-24 10:36:52 - Pipeline - INFO - Successfully converted 9 energy bins to FITS
2026-08-24 10:36:52 - Pipeline - INFO - Creating HEALPix map from 9 FITS files
2026-08-24 10:36:52 - Pipeline - INFO - Energy bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']
2026-08-24 10:36:52 - Pipeline - INFO - Executing HealpixSigFluxMap command:

Created FITS files: [PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB2C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB3C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB4C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB5C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB6C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB7C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB8C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB9C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB10C0.fits.gz')]
Path: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit

2026-08-24 10:37:22 - Pipeline - INFO - HEALPix map created successfully: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual.fits
2026-08-24 10:37:23 - Pipeline - INFO - Max value in residual map: nan

ROI center in Celestial Coordintes = None, None
Loading Celestial Map
Fits File loaded
Degrees per pixel: 1.0
Peak intensity pixel location: (np.int64(0), np.int64(0))
Peak intensity sky location: <SkyCoord (ICRS): (ra, dec) in deg
    (nan, nan)>
Peak intensity value: nan
path.parent: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit

10:34:35 WARNING   The naima package is not available. Models    ]8;id=9358362;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=9358363;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
10:34:35 WARNING   The naima package is not available. Models    ]8;id=6678686;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=6678687;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
10:34:35 WARNING   The naima package is not available. Models    ]8;id=6306288;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=6306289;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
10:34:35 WARNING   The naima package is not available. Models    ]8;id=8326238;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=8326239;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=6678693;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=6678694;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=9358369;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=9358370;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=6306295;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=6306296;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=8326245;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=8326246;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
10:34:36 WARNING   The ebltable package is not available.       ]8;id=8326253;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=8326254;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
10:34:36 WARNING   The ebltable package is not available.       ]8;id=9358377;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=9358378;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
10:34:36 WARNING   The ebltable package is not available.       ]8;id=6678701;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=6678702;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
10:34:36 WARNING   The ebltable package is not available.       ]8;id=6306303;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=6306304;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
10:34:36 INFO      Starting 3ML!                                  ]8;id=9358385;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9358386;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
10:34:36 INFO      Starting 3ML!                                  ]8;id=6306311;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=6306312;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
10:34:36 INFO      Starting 3ML!                                  ]8;id=6678709;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=6678710;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=6306318;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=6306319;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=9358392;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9358393;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=6678716;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=6678717;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
10:34:36 INFO      Starting 3ML!                                  ]8;id=8326261;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8326262;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
         WARNING   but are inform you about optional packages     ]8;id=6306325;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=6306326;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=9358399;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9358400;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=6678723;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=6678724;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING    to disable these messages, turn off           ]8;id=6306332;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=6306333;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=9358406;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9358407;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=6678730;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=6678731;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING   WARNINGs here are NOT errors                   ]8;id=8326268;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8326269;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   no display variable set. using backend for     ]8;id=6306339;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=6306340;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=9358413;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9358414;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=6678737;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=6678738;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   but are inform you about optional packages     ]8;id=8326275;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8326276;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING    to disable these messages, turn off           ]8;id=8326282;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8326283;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING   no display variable set. using backend for     ]8;id=8326289;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8326290;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
In file included from input_line_36:In file included from In file included from input_line_36:input_line_361::
1In file included from :
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.hIn file included from :/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h26::
In file included from In file included from input_line_36/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h::1192:
26In file included from :
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.hIn file included from :
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h:
:92In file included from :
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h::26::
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.hIn file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h26::
8In file included from :/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h9::9292:
:
8/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h::98:::  :warning: 8'Py_single_input' macro redefined [-Wmacro-redefined]:
9: 9warning: warning: 'Py_single_input' macro redefined [-Wmacro-redefined]'Py_single_input' macro redefined [-Wmacro-redefined]:# dwarning: e
fin
e P'Py_single_input' macro redefined [-Wmacro-redefined]y_s
ing#l#ed_eifnipnuet  P2y5_#6sdienfgilnee_ dPeyf_iine
nsp        ^uiPnyg_
sinlgel_ei_nti n2p5u6tp u2t5 6:
49        ^:

562:5 6note:
previous definition is here        ^

        ^
:49:56: note: tprevious definition is heree
m:p49l:a56t:e  note: <previous definition is herec:l49a:
stse mTp>56 : note: lprevious definition is heret
empalt[a[tneo d<icslcaaer d<]ct]le mcposnss tTe>x plra tT[*[ nloaduinsedc a<racslsadse]sr]  Tc>o nTs>t ([ T[[*n[ondoiedsxcparr ids]c]a rcTo*n sltaeuxnpdde]r]( T *p )pc)o nn oneosetxecxrpre pTt*;  l a u/n/d eCrx cTe*+ (+lT1a*u npp)7t,;  d   e/r/n( oCe+x+c1e7p,ntoT;d* i sncoadrids  spi)n cneo cCa+r+d2 0s
ienxccee pCt+;+ 2 0
/                                                       ^/
 C  // C                                                       ^++1
7, nodiscard si++17, nncoed iCs+c+a2r0d
                                                        ^s
ince C++20
                                                       ^
10:34:37 WARNING   Multinest minimizer not available        ]8;id=9358421;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=9358422;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
10:34:37 WARNING   Multinest minimizer not available        ]8;id=6306347;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=6306348;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
10:34:37 WARNING   Multinest minimizer not available        ]8;id=6678745;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=6678746;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
10:34:37 WARNING   Multinest minimizer not available        ]8;id=8326297;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=8326298;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   PyGMO is not available                   ]8;id=6306354;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=6306355;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=8326304;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=8326305;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=9358428;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=9358429;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=6678752;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=6678753;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   Could not import plugin FermiLATLike.py. Do   ]8;id=6306361;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=6306362;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#126\126]8;;\
                  you have the relative instrument software
                  installed and configured?

In [22]:
from typing import List
def _as_list(value) -> List[str]:
    if value is None:
        return []
    return value if isinstance(value, list) else [value]

In [31]:
config = ConfigManager('config.yaml')
model = fit_output.model
baseline_log_like = fit_output.log_like
source_names = list(model.sources.keys())
alt_models = _as_list(config.get('fitting.alternate_spatial_models'))
alt_spectra = _as_list(config.get('fitting.alternate_spectral_models'))
coord_range = config.get('fitting.extended_source_coord_range', 1.0)
logger.info(f"Sources in the model: {source_names}")
logger.info(f"Baseline log-likelihood: {baseline_log_like}")
logger.info(f"Alternate spatial models: {alt_models}")
logger.info(f"Alternate spectral models: {alt_spectra}")

2026-08-24 10:44:07 - Pipeline - INFO - Sources in the model: ['Source0', 'Source1']
2026-08-24 10:44:07 - Pipeline - INFO - Baseline log-likelihood: 200054.62190030178
2026-08-24 10:44:07 - Pipeline - INFO - Alternate spatial models: ['Gaussian_on_sphere']
2026-08-24 10:44:07 - Pipeline - INFO - Alternate spectral models: ['Cutoff_powerlaw', 'Log_parabola']

In [ ]:
# # for sourcename in source_names:
# #     source = model.sources[sourcename]
# #     print(f"Checking source {source.name} for extension test")
# #     if source.name == 'URM':
# #         params = list(source.spatial_shape.parameters.items())
# #         # params = {k: v.value for k, v in params}
# #         print(f"Source {source.name} spatial shape: {params[0][1]}")
# #         params[0][1].free = False
# #         print(f"Source {source.name} spatial shape: {params[0][1].free}")

# for sourcename in source_names:
#     source = model.sources[sourcename]
#     print(f"Checking source {source.name} for extension test")
#     if source.name == 'URM':
#         params = list(source.spectrum.main._children.items())
#         spec_name, spec_func = params[0]
#         for pname, p in spec_func.parameters.items():
#             p.free = False
#         print(f"Source {source.name} spectrum: {spec_func}")
#         # params = {k: v.value for k, v in params}
#         # params[0][1].free = True
#         # print(f"Source {source.name} spatial shape: {params[0][1].free}")

In [ ]:
result = fit_output 
%load_ext autoreload
%autoreload 2
import importlib
import model_generator
import source_fitter

importlib.reload(source_fitter)
importlib.reload(model_generator)

alt_models = _as_list(config.get('fitting.alternate_spatial_models'))
if not alt_models:
    logger.info('No fitting.alternate_spatial_models configured; skipping extension test')

free_dbe = config.get('fitting.free_diffuse_norm', False)
threshold = config.get('likelihood_thresholds.extension_test', 16)
coord_range = config.get('fitting.extended_source_coord_range', 1.0)
runner = FitRunner(
    config_path=str(config.config_file),
    logger=logger,
    roi_template=config.get('roi.roi_template_path'),
)

model = fit_result.model
baseline_log_like = fit_result.log_like
source_names = list(model.sources.keys())
for source_name in source_names:
    if source_name == 'URM':
        logger.info(f'Skipping extension test for {source_name} (URM source)')
        continue
    other_sources = [n for n in model.sources.keys() if n != source_name]
    best_log_like = baseline_log_like
    best_model = model

    for alt_shape in alt_models:
        trial_model = model_generator.ModelGenerator.swap_spatial_shape(
            model, source_name, alt_shape, coord_range=coord_range, logger=logger,
        )
        model_generator.ModelGenerator.set_free(trial_model, other_sources, kind='spatial', free=False, free_diffuse=free_dbe, logger=logger)
        model_generator.ModelGenerator.set_free(trial_model, other_sources, kind='spectral', free=True, free_diffuse=free_dbe, logger=logger)

        step_name = f'Step2-{source_name}-Extension-{alt_shape}'
        step_dir = directory_manager.get_step_results_dir(step_name)
        model_file = model_generator.ModelGenerator.write_model_from_live(
            trial_model, str(directory_manager.get_model_file_path(step_name)), logger=logger,
        )
        trial_model.save("{1}/{0}.yml".format('curModel', step_dir), overwrite=True)
        model_generator.ModelGenerator.write_model_file_from_yaml("{1}/{0}.yml".format('curModel', step_dir), "{1}/{0}.model".format('curModel', step_dir), logger=logger)

        trial_result = runner.fit(
            model_file=str(model_file),
            step_dir=str(step_dir),
            compute_err=config.get('error_and_TS.error_extension', True),
            make_maps=False,
        )

        # logger.info(trial_model)
        # ModelGenerator.set_free(trial_model, other_sources, kind='spatial', free=False)
        # ModelGenerator.set_free(trial_model, other_sources, kind='spectral', free=False)

        # step_name = f'Step2-{source_name}-Extension-{alt_shape}'
        # step_dir = directory_manager.get_step_results_dir(step_name)
        # model_file = ModelGenerator.write_model_from_live(
        #     trial_model, str(directory_manager.get_model_file_path(step_name)), logger=logger,
        # )

In [42]:
result = fit_output 

%load_ext autoreload
%autoreload 2
import importlib
import model_generator
import source_fitter
importlib.reload(source_fitter)
importlib.reload(model_generator)
logger.info('Starting extension fit')


if config.get('fitting.run_extension_test', True):
    result_ext = source_fitter.run_extension_test(result, config, logger, directory_manager)

2026-08-24 11:06:55 - Pipeline - INFO - Starting extension fit
2026-08-24 11:06:55 - Pipeline - INFO - Diffuse background normalization status during spectrum test: True
2026-08-24 11:06:55 - Pipeline - INFO - Current best log-likelihood: 200054.622
2026-08-24 11:06:55 - Pipeline - INFO - Spatial shape of source Point_Source, Alternate model Gaussian_on_sphere
2026-08-24 11:06:55 - Pipeline - INFO - SOURCE Source1 : param ra -> FIXED (not in param_names)
2026-08-24 11:06:55 - Pipeline - INFO - SOURCE Source1 : param dec -> FIXED (not in param_names)
2026-08-24 11:06:55 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 11:06:55 - Pipeline - INFO - SOURCE Source1 : param K -> free=True
2026-08-24 11:06:55 - Pipeline - INFO - SOURCE Source1 : param piv -> FIXED (not in param_names)
2026-08-24 11:06:55 - Pipeline - INFO - SOURCE Source1 : param index -> free=True
2026-08-24 11:06:55 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source0-Extension-Gaussian_on_sphere/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source0-Extension-Gaussian_on_sphere  with compute_err=False, compute_TS=False, make_maps=True
2026-08-24 11:06:55 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 11:06:55 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 11:06:55 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source0-Extension-Gaussian_on_sphere/curModel.model
2026-08-24 11:06:55 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 11:06:55 - Pipeline - INFO - ROI center: 83, 22
2026-08-24 11:06:55 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
['Source1', 'Source0']
83 22 15
Center of ROI  RA: 83.0000 Dec: 22.0000 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source1          85.7157    23.4480   2.893 degrees
Source0          83.6336    22.0119   0.588 degrees

2026-08-24 11:07:09 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  200484.35181024385
TOTAL =  200484.35
CURRENT =  200484.35181024385
CURRENT =  200484.35

Best fit values:

,result,unit
parameter,,
Source1.spectrum.main.Powerlaw.K,(1.1879375032226258 +/- 0) x 10^-24,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.3846499347338517 +/- 0,
Source0.Gaussian_on_sphere.sigma,(6.823307634709172 +/- 0) x 10^-2,deg
Source0.spectrum.main.Powerlaw.K,(9.528289445798992 +/- 0) x 10^-23,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.586286668074669 +/- 0,

Correlation matrix:

nan nan nan nan nan
nan nan nan nan nan
nan nan nan nan nan
nan nan nan nan nan
nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC       200484.35181
total      200484.35181

Values of statistical measures:

     statistical measures
AIC         400978.703649
BIC         401041.497061

Best fit values:

,result,unit
parameter,,
Source1.spectrum.main.Powerlaw.K,(1.1879375032226258 +/- 0) x 10^-24,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.3846499347338517 +/- 0,
Source0.Gaussian_on_sphere.sigma,(6.823307634709172 +/- 0) x 10^-2,deg
Source0.spectrum.main.Powerlaw.K,(9.528289445798992 +/- 0) x 10^-23,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.586286668074669 +/- 0,

Correlation matrix:

nan nan nan nan nan
nan nan nan nan nan
nan nan nan nan nan
nan nan nan nan nan
nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC       200484.35181
total      200484.35181

Values of statistical measures:

     statistical measures
AIC         400978.703649
BIC         401041.497061

2026-08-24 11:07:19 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source0-Extension-Gaussian_on_sphere/likelihoodResults.fits
2026-08-24 11:07:19 - Pipeline - INFO - Saving HAL output maps
2026-08-24 11:07:19 - Pipeline - INFO - SAVE A BIG MAP
2026-08-24 11:07:40 - Pipeline - INFO - Writing model map...
2026-08-24 11:07:40 - Pipeline - INFO - Fit Step2-Source0-Extension-Gaussian_on_sphere: -logL=200484.352, AIC=400978.704 (0.76 min)
2026-08-24 11:07:40 - Pipeline - INFO - Extension test Source0 -> Gaussian_on_sphere: delta_TS=-859.46 (threshold 16)
2026-08-24 11:07:40 - Pipeline - INFO - Rejected alternate spatial model Gaussian_on_sphere for Source0; skipping TS computation
2026-08-24 11:07:40 - Pipeline - INFO - Current best log-likelihood: 200054.622
2026-08-24 11:07:40 - Pipeline - INFO - Spatial shape of source Point_Source, Alternate model Gaussian_on_sphere
2026-08-24 11:07:40 - Pipeline - INFO - SOURCE Source0 : param ra -> FIXED (not in param_names)
2026-08-24 11:07:40 - Pipeline - INFO - SOURCE Source0 : param dec -> FIXED (not in param_names)
2026-08-24 11:07:40 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 11:07:40 - Pipeline - INFO - SOURCE Source0 : param K -> free=True
2026-08-24 11:07:40 - Pipeline - INFO - SOURCE Source0 : param piv -> FIXED (not in param_names)
2026-08-24 11:07:40 - Pipeline - INFO - SOURCE Source0 : param index -> free=True
2026-08-24 11:07:40 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source1-Extension-Gaussian_on_sphere/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source1-Extension-Gaussian_on_sphere  with compute_err=False, compute_TS=False, make_maps=True
2026-08-24 11:07:40 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 11:07:40 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 11:07:40 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source1-Extension-Gaussian_on_sphere/curModel.model
2026-08-24 11:07:40 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 11:07:40 - Pipeline - INFO - ROI center: 83, 22
2026-08-24 11:07:40 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

['Source0', 'Source1']
83 22 15
Center of ROI  RA: 83.0000 Dec: 22.0000 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source0          83.6336    22.0119   0.588 degrees
Source1          85.7157    23.4480   2.893 degrees

2026-08-24 11:07:54 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  199969.05402032152
TOTAL =  199969.05
CURRENT =  199969.05402032152
CURRENT =  199969.05

Best fit values:

,result,unit
parameter,,
Source0.spectrum.main.Powerlaw.K,(9.129512232835433 +/- 0) x 10^-23,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.5878762977942573 +/- 0,
Source1.Gaussian_on_sphere.sigma,1.0066532244553366 +/- 0,deg
Source1.spectrum.main.Powerlaw.K,(1.3638697533377249 +/- 0) x 10^-23,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.1299171325466615 +/- 0,

Correlation matrix:

nan nan nan nan nan
nan nan nan nan nan
nan nan nan nan nan
nan nan nan nan nan
nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC       199969.05402
total      199969.05402

Values of statistical measures:

     statistical measures
AIC         399948.108069
BIC         400010.901481

Best fit values:

,result,unit
parameter,,
Source0.spectrum.main.Powerlaw.K,(9.129512232835433 +/- 0) x 10^-23,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.5878762977942573 +/- 0,
Source1.Gaussian_on_sphere.sigma,1.0066532244553366 +/- 0,deg
Source1.spectrum.main.Powerlaw.K,(1.3638697533377249 +/- 0) x 10^-23,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.1299171325466615 +/- 0,

Correlation matrix:

nan nan nan nan nan
nan nan nan nan nan
nan nan nan nan nan
nan nan nan nan nan
nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC       199969.05402
total      199969.05402

Values of statistical measures:

     statistical measures
AIC         399948.108069
BIC         400010.901481

2026-08-24 11:08:02 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source1-Extension-Gaussian_on_sphere/likelihoodResults.fits
2026-08-24 11:08:02 - Pipeline - INFO - Saving HAL output maps
2026-08-24 11:08:02 - Pipeline - INFO - SAVE A BIG MAP
2026-08-24 11:08:26 - Pipeline - INFO - Writing model map...
2026-08-24 11:08:27 - Pipeline - INFO - Fit Step2-Source1-Extension-Gaussian_on_sphere: -logL=199969.054, AIC=399948.108 (0.77 min)
2026-08-24 11:08:27 - Pipeline - INFO - Extension test Source1 -> Gaussian_on_sphere: delta_TS=171.14 (threshold 16)
2026-08-24 11:08:27 - Pipeline - INFO - delta_TS above threshold; computing per-source TS for Step2-Source1-Extension-Gaussian_on_sphere
2026-08-24 11:08:27 - Pipeline - INFO - Calculating TS for all sources in the model
2026-08-24 11:08:27 - Pipeline - INFO - Computing TS for source: Source0
2026-08-24 11:08:31 - Pipeline - INFO - TS for source Source0: 95266.54488045361
2026-08-24 11:08:31 - Pipeline - INFO - Computing TS for source: Source1

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  247602.32646054833
TOTAL =  247602.33
CURRENT =  247602.32646054833
CURRENT =  247602.33

2026-08-24 11:08:31 - Pipeline - INFO - TS for source Source1: 226.66692540573422
2026-08-24 11:08:31 - Pipeline - INFO - Accepted alternate spatial model Gaussian_on_sphere for Source1

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  200082.3874830244
TOTAL =  200082.39
CURRENT =  200082.3874830244
CURRENT =  200082.39

11:06:58 WARNING   The naima package is not available. Models    ]8;id=7016736;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=7016737;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
11:06:58 WARNING   The naima package is not available. Models    ]8;id=13346169;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=13346170;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
11:06:58 WARNING   The naima package is not available. Models    ]8;id=13350098;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=13350099;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
11:06:58 WARNING   The naima package is not available. Models    ]8;id=4618462;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=4618463;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=7016743;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=7016744;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=13346176;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=13346177;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=4618469;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=4618470;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=13350105;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=13350106;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The ebltable package is not available.       ]8;id=13350113;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=13350114;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=7016751;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=7016752;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=4618477;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=4618478;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=13346184;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=13346185;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
11:06:59 INFO      Starting 3ML!                                  ]8;id=13346192;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=13346193;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
11:06:59 INFO      Starting 3ML!                                  ]8;id=13350121;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=13350122;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
11:06:59 INFO      Starting 3ML!                                  ]8;id=4618485;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=4618486;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=13346199;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=13346200;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=13350128;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=13350129;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
11:06:59 INFO      Starting 3ML!                                  ]8;id=7016759;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=7016760;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=4618492;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=4618493;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   but are inform you about optional packages     ]8;id=13346206;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=13346207;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=13350135;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=13350136;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   WARNINGs here are NOT errors                   ]8;id=7016766;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=7016767;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   but are inform you about optional packages     ]8;id=4618499;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=4618500;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING    to disable these messages, turn off           ]8;id=13346213;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=13346214;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=13350142;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=13350143;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING   but are inform you about optional packages     ]8;id=7016773;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=7016774;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING    to disable these messages, turn off           ]8;id=4618506;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=4618507;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING   no display variable set. using backend for     ]8;id=13346220;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=13346221;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=13350149;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=13350150;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING    to disable these messages, turn off           ]8;id=7016780;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=7016781;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING   no display variable set. using backend for     ]8;id=4618513;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=4618514;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=7016787;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=7016788;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
In file included from input_line_36In file included from In file included from input_line_36:input_line_36In file included from :1:
1::
1In file included from input_line_36In file included from :/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h1::
26In file included from :
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.hIn file included from :/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h:
26:In file included from 92/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h:
:/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h26::
26In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h::892::
9/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h::
:
In file included from In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h::92:928:
:9/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h:: 8 warning: warning: 'Py_single_input' macro redefined [-Wmacro-redefined]'Py_single_input' macro redefined [-Wmacro-redefined]
::
9/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h
:8::9 :warning:  'Py_single_input' macro redefined [-Wmacro-redefined]#
def#iwarning: n'Py_single_input' macro redefined [-Wmacro-redefined]e
 dPe#f#dideneef iPyny__ssfiiinngel eP_yie_nnpgulte  _Piyn_psu2s5i6nignlgel_ei_nipnupt
         ^2
5u6tt  225:649
:        ^565
: note: previous definition is here

        ^
6
:        ^49
t:e49m:::5649::p lnote: aprevious definition is heret
56: note: 56previous definition is here
et:e mnote: previous definition is heret
epmlpal ate t<ec<lcalsass sTt>e m[p[lnao dTi>s tcea r<dc][ [<ncllaassosd iTs>c a[s[ nTorddi]s>]  [c[ocnnosdti]eaxrpds]c]a rc oTn* s ctleaxuprndd]e]r (cro nTs*tT olnasutnedxeprr( TT**e xlpa upn)dre rT(* T *l apu)n d*e rp()n oneoxTc*e ppet);  n n o/e/xo cCe+x+c1e7p,t ;npotd;i s c a r d  //s/i nCceex c+e/+ 1C7+,+ 1n7o,d inpotd;issccaa r d  rsdi n/c/e  CC+++s1i7n,+ 2n0o
dcies cC                                                       ^+
+20C
+                                                       ^+
20
                                                       ^a
rd since C++20
                                                       ^
         WARNING   Multinest minimizer not available        ]8;id=13346228;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=13346229;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=7016795;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=7016796;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=4618521;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=4618522;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=13350157;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=13350158;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   PyGMO is not available                   ]8;id=7016802;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=7016803;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=13346235;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=13346236;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=4618528;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=4618529;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=13350164;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=13350165;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   Could not import plugin FermiLATLike.py. Do   ]8;id=13346242;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=13346243;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#126\126]8;;\
                  you have the relative instrument software
                  installed and configured?

In [43]:
result_ext

FitResult(model=Model summary:
==============

                  N
Point sources     1
Extended sources  1
Particle sources  0

Free parameters (5):
--------------------

                                         value min_value max_value  \
Source0.spectrum.main.Powerlaw.K           0.0       0.0       0.0
Source0.spectrum.main.Powerlaw.index -2.587876      -3.0      -1.0
Source1.Gaussian_on_sphere.sigma      1.006653      0.01       3.0
Source1.spectrum.main.Powerlaw.K           0.0       0.0       0.0
Source1.spectrum.main.Powerlaw.index -2.129917      -3.0      -1.0

                                                unit
Source0.spectrum.main.Powerlaw.K      keV-1 s-1 cm-2
Source0.spectrum.main.Powerlaw.index
Source1.Gaussian_on_sphere.sigma                 deg
Source1.spectrum.main.Powerlaw.K      keV-1 s-1 cm-2
Source1.spectrum.main.Powerlaw.index

Fixed parameters (7):
(abridged. Use complete=True to see all fixed parameters)


Properties (0):
--------------------

(none)


Linked parameters (0):
----------------------

(none)

Independent variables:
----------------------

(none)

Linked functions (0):
----------------------

(none)
, log_like=199969.05402032152, aic=399948.1080691791, ts={'Source0': 95266.54488045361, 'Source1': 226.66692540573422}, model_map_path=PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source1-Extension-Gaussian_on_sphere/model_fit.hd5'), residual_map_path=PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source1-Extension-Gaussian_on_sphere/residual_fit.hd5'), step_dir=PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source1-Extension-Gaussian_on_sphere'), fitter=<pipeline_fitmodel.threeMLFit object at 0x37a365790>)

In [44]:
%load_ext autoreload
%autoreload 2
import importlib
import model_generator
import source_fitter
importlib.reload(source_fitter)
importlib.reload(model_generator)
logger.info('Starting extension fit')


if config.get('fitting.run_spectrum_test', True):
    result_spectrum_test = source_fitter.run_spectrum_test(result_ext, config, logger, directory_manager)

2026-08-24 11:08:32 - Pipeline - INFO - Starting extension fit
2026-08-24 11:08:32 - Pipeline - INFO - Diffuse background normalization status during spectrum test: True
2026-08-24 11:08:32 - Pipeline - INFO - Swapping Source0 spectral shape from Powerlaw to Cutoff_powerlaw
2026-08-24 11:08:32 - Pipeline - INFO - New spectrum class: dict_keys(['K', 'piv', 'index', 'xc'])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

2026-08-24 11:08:32 - Pipeline - INFO - Swapped Source0 spectral shape -> Cutoff_powerlaw
2026-08-24 11:08:32 - Pipeline - INFO - SOURCE Source1 : param lon0 -> FIXED (not in param_names)
2026-08-24 11:08:32 - Pipeline - INFO - SOURCE Source1 : param lat0 -> FIXED (not in param_names)
2026-08-24 11:08:32 - Pipeline - INFO - SOURCE Source1 : param sigma -> free=True
2026-08-24 11:08:32 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 11:08:32 - Pipeline - INFO - SOURCE Source1 : param K -> free=True
2026-08-24 11:08:32 - Pipeline - INFO - SOURCE Source1 : param piv -> FIXED (not in param_names)
2026-08-24 11:08:32 - Pipeline - INFO - SOURCE Source1 : param index -> free=True
2026-08-24 11:08:32 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source0-Spectrum-Cutoff_powerlaw/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source0-Spectrum-Cutoff_powerlaw  with compute_err=False, compute_TS=False, make_maps=False
2026-08-24 11:08:32 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 11:08:32 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 11:08:32 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source0-Spectrum-Cutoff_powerlaw/curModel.model
2026-08-24 11:08:32 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 11:08:32 - Pipeline - INFO - ROI center: 83, 22
2026-08-24 11:08:32 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

['Source0', 'Source1']
83 22 15
Center of ROI  RA: 83.0000 Dec: 22.0000 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source0          83.6336    22.0119   0.588 degrees
Source1          85.7157    23.4480   2.893 degrees

2026-08-24 11:08:49 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  199639.18900017382
TOTAL =  199639.19
CURRENT =  199639.18900017382
CURRENT =  199639.19

Best fit values:

,result,unit
parameter,,
Source1.Gaussian_on_sphere.sigma,1.0335861838984186 +/- 0,deg
Source1.spectrum.main.Powerlaw.K,(1.428422005482404 +/- 0) x 10^-23,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.1473765917096475 +/- 0,
Source0.spectrum.main.Cutoff_powerlaw.K,(6.7466500517571735 +/- 0) x 10^-21,1 / (keV s cm2)
Source0.spectrum.main.Cutoff_powerlaw.index,-2.39151714104079 +/- 0,
Source0.spectrum.main.Cutoff_powerlaw.xc,(2.679956472528821 +/- 0) x 10^10,keV

Correlation matrix:

nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC         199639.189
total        199639.189

Values of statistical measures:

     statistical measures
AIC         399290.378040
BIC         399365.730129

Best fit values:

,result,unit
parameter,,
Source1.Gaussian_on_sphere.sigma,1.0335861838984186 +/- 0,deg
Source1.spectrum.main.Powerlaw.K,(1.428422005482404 +/- 0) x 10^-23,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.1473765917096475 +/- 0,
Source0.spectrum.main.Cutoff_powerlaw.K,(6.7466500517571735 +/- 0) x 10^-21,1 / (keV s cm2)
Source0.spectrum.main.Cutoff_powerlaw.index,-2.39151714104079 +/- 0,
Source0.spectrum.main.Cutoff_powerlaw.xc,(2.679956472528821 +/- 0) x 10^10,keV

Correlation matrix:

nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC         199639.189
total        199639.189

Values of statistical measures:

     statistical measures
AIC         399290.378040
BIC         399365.730129

2026-08-24 11:09:00 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source0-Spectrum-Cutoff_powerlaw/likelihoodResults.fits
2026-08-24 11:09:00 - Pipeline - INFO - Fit Step3-Source0-Spectrum-Cutoff_powerlaw: -logL=199639.189, AIC=399290.378 (0.46 min)
2026-08-24 11:09:00 - Pipeline - INFO - Spectrum test Source0 -> Cutoff_powerlaw: delta_TS=659.73 (threshold 16)
2026-08-24 11:09:00 - Pipeline - INFO - delta_TS above threshold; computing per-source TS for Step3-Source0-Spectrum-Cutoff_powerlaw
2026-08-24 11:09:00 - Pipeline - INFO - Calculating TS for all sources in the model
2026-08-24 11:09:00 - Pipeline - INFO - Computing TS for source: Source0
2026-08-24 11:09:04 - Pipeline - INFO - TS for source Source0: 95926.27466099878
2026-08-24 11:09:04 - Pipeline - INFO - Computing TS for source: Source1

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  247602.3263306732
TOTAL =  247602.33
CURRENT =  247602.3263306732
CURRENT =  247602.33

2026-08-24 11:09:05 - Pipeline - INFO - TS for source Source1: 229.72775282373186
2026-08-24 11:09:05 - Pipeline - INFO - Accepted alternate spectral model Cutoff_powerlaw for Source0
2026-08-24 11:09:05 - Pipeline - INFO - Swapping Source0 spectral shape from Powerlaw to Log_parabola
2026-08-24 11:09:05 - Pipeline - INFO - New spectrum class: dict_keys(['K', 'piv', 'alpha', 'beta'])

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  199754.0528765857
TOTAL =  199754.05
CURRENT =  199754.0528765857
CURRENT =  199754.05

2026-08-24 11:09:05 - Pipeline - INFO - Swapped Source0 spectral shape -> Log_parabola
2026-08-24 11:09:05 - Pipeline - INFO - SOURCE Source1 : param lon0 -> FIXED (not in param_names)
2026-08-24 11:09:05 - Pipeline - INFO - SOURCE Source1 : param lat0 -> FIXED (not in param_names)
2026-08-24 11:09:05 - Pipeline - INFO - SOURCE Source1 : param sigma -> free=True
2026-08-24 11:09:05 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 11:09:05 - Pipeline - INFO - SOURCE Source1 : param K -> free=True
2026-08-24 11:09:05 - Pipeline - INFO - SOURCE Source1 : param piv -> FIXED (not in param_names)
2026-08-24 11:09:05 - Pipeline - INFO - SOURCE Source1 : param index -> free=True
2026-08-24 11:09:05 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source0-Spectrum-Log_parabola/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source0-Spectrum-Log_parabola  with compute_err=False, compute_TS=False, make_maps=False
2026-08-24 11:09:05 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 11:09:05 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 11:09:05 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source0-Spectrum-Log_parabola/curModel.model
2026-08-24 11:09:05 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 11:09:05 - Pipeline - INFO - ROI center: 83, 22
2026-08-24 11:09:05 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

['Source0', 'Source1']
83 22 15
Center of ROI  RA: 83.0000 Dec: 22.0000 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source0          83.6336    22.0119   0.588 degrees
Source1          85.7157    23.4480   2.893 degrees

2026-08-24 11:09:21 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  199633.5249919069
TOTAL =  199633.52
CURRENT =  199633.5249919069
CURRENT =  199633.52

Best fit values:

,result,unit
parameter,,
Source1.Gaussian_on_sphere.sigma,1.0351343767333532 +/- 0,deg
Source1.spectrum.main.Powerlaw.K,(1.4368733718045776 +/- 0) x 10^-23,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.1534749051309254 +/- 0,
Source0.spectrum.main.Log_parabola.K,(6.56336149442057 +/- 0) x 10^-21,1 / (keV s cm2)
Source0.spectrum.main.Log_parabola.alpha,-2.5020489596588056 +/- 0,
Source0.spectrum.main.Log_parabola.beta,(1.0012314357420093 +/- 0) x 10^-1,

Correlation matrix:

nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      199633.524992
total     199633.524992

Values of statistical measures:

     statistical measures
AIC         399279.050024
BIC         399354.402112

Best fit values:

,result,unit
parameter,,
Source1.Gaussian_on_sphere.sigma,1.0351343767333532 +/- 0,deg
Source1.spectrum.main.Powerlaw.K,(1.4368733718045776 +/- 0) x 10^-23,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.1534749051309254 +/- 0,
Source0.spectrum.main.Log_parabola.K,(6.56336149442057 +/- 0) x 10^-21,1 / (keV s cm2)
Source0.spectrum.main.Log_parabola.alpha,-2.5020489596588056 +/- 0,
Source0.spectrum.main.Log_parabola.beta,(1.0012314357420093 +/- 0) x 10^-1,

Correlation matrix:

nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan
nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      199633.524992
total     199633.524992

Values of statistical measures:

     statistical measures
AIC         399279.050024
BIC         399354.402112

2026-08-24 11:09:27 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source0-Spectrum-Log_parabola/likelihoodResults.fits
2026-08-24 11:09:27 - Pipeline - INFO - Fit Step3-Source0-Spectrum-Log_parabola: -logL=199633.525, AIC=399279.050 (0.36 min)
2026-08-24 11:09:27 - Pipeline - INFO - Spectrum test Source0 -> Log_parabola: delta_TS=11.33 (threshold 16)
2026-08-24 11:09:27 - Pipeline - INFO - Rejected alternate spectral model Log_parabola for Source0; skipping TS computation
2026-08-24 11:09:27 - Pipeline - INFO - Swapping Source1 spectral shape from Powerlaw to Cutoff_powerlaw
2026-08-24 11:09:27 - Pipeline - INFO - New spectrum class: dict_keys(['K', 'piv', 'index', 'xc'])
2026-08-24 11:09:27 - Pipeline - INFO - Swapped Source1 spectral shape -> Cutoff_powerlaw
2026-08-24 11:09:27 - Pipeline - INFO - SOURCE Source0 : param ra -> FIXED (not in param_names)
2026-08-24 11:09:27 - Pipeline - INFO - SOURCE Source0 : param dec -> FIXED (not in param_names)
2026-08-24 11:09:27 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 11:09:27 - Pipeline - INFO - SOURCE Source0 : param K -> free=True
2026-08-24 11:09:27 - Pipeline - INFO - SOURCE Source0 : param piv -> FIXED (not in param_names)
2026-08-24 11:09:27 - Pipeline - INFO - SOURCE Source0 : param index -> free=True
2026-08-24 11:09:27 - Pipeline - INFO - SOURCE Source0 : param xc -> free=True
2026-08-24 11:09:27 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source1-Spectrum-Cutoff_powerlaw/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source1-Spectrum-Cutoff_powerlaw  with compute_err=False, compute_TS=False, make_maps=False
2026-08-24 11:09:27 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 11:09:27 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 11:09:27 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source1-Spectrum-Cutoff_powerlaw/curModel.model
2026-08-24 11:09:27 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 11:09:27 - Pipeline - INFO - ROI center: 83, 22
2026-08-24 11:09:27 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

['Source0', 'Source1']
83 22 15
Center of ROI  RA: 83.0000 Dec: 22.0000 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source0          83.6336    22.0119   0.588 degrees
Source1          85.7157    23.4480   2.893 degrees

2026-08-24 11:09:42 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  199639.02728332815
TOTAL =  199639.03
CURRENT =  199639.02728332815
CURRENT =  199639.03

Best fit values:

,result,unit
parameter,,
Source0.spectrum.main.Cutoff_powerlaw.K,(6.74708025272963 +/- 0) x 10^-21,1 / (keV s cm2)
Source0.spectrum.main.Cutoff_powerlaw.index,-2.3918025261184894 +/- 0,
Source0.spectrum.main.Cutoff_powerlaw.xc,(2.682265498822541 +/- 0) x 10^10,keV
Source1.Gaussian_on_sphere.sigma,1.0265349050440211 +/- 0,deg
Source1.spectrum.main.Cutoff_powerlaw.K,(4.101309012643499 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Cutoff_powerlaw.index,-2.020434943889856 +/- 0,
Source1.spectrum.main.Cutoff_powerlaw.xc,(1.9361058337260437 +/- 0) x 10^11,keV

Correlation matrix:

nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      199639.027283
total     199639.027283

Values of statistical measures:

     statistical measures
AIC         399292.054620
BIC         399379.965383

Best fit values:

,result,unit
parameter,,
Source0.spectrum.main.Cutoff_powerlaw.K,(6.74708025272963 +/- 0) x 10^-21,1 / (keV s cm2)
Source0.spectrum.main.Cutoff_powerlaw.index,-2.3918025261184894 +/- 0,
Source0.spectrum.main.Cutoff_powerlaw.xc,(2.682265498822541 +/- 0) x 10^10,keV
Source1.Gaussian_on_sphere.sigma,1.0265349050440211 +/- 0,deg
Source1.spectrum.main.Cutoff_powerlaw.K,(4.101309012643499 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Cutoff_powerlaw.index,-2.020434943889856 +/- 0,
Source1.spectrum.main.Cutoff_powerlaw.xc,(1.9361058337260437 +/- 0) x 10^11,keV

Correlation matrix:

nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      199639.027283
total     199639.027283

Values of statistical measures:

     statistical measures
AIC         399292.054620
BIC         399379.965383

2026-08-24 11:10:12 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source1-Spectrum-Cutoff_powerlaw/likelihoodResults.fits
2026-08-24 11:10:12 - Pipeline - INFO - Fit Step3-Source1-Spectrum-Cutoff_powerlaw: -logL=199639.027, AIC=399292.055 (0.76 min)
2026-08-24 11:10:12 - Pipeline - INFO - Spectrum test Source1 -> Cutoff_powerlaw: delta_TS=0.32 (threshold 16)
2026-08-24 11:10:12 - Pipeline - INFO - Rejected alternate spectral model Cutoff_powerlaw for Source1; skipping TS computation
2026-08-24 11:10:12 - Pipeline - INFO - Swapping Source1 spectral shape from Powerlaw to Log_parabola
2026-08-24 11:10:12 - Pipeline - INFO - New spectrum class: dict_keys(['K', 'piv', 'alpha', 'beta'])
2026-08-24 11:10:12 - Pipeline - INFO - Swapped Source1 spectral shape -> Log_parabola
2026-08-24 11:10:12 - Pipeline - INFO - SOURCE Source0 : param ra -> FIXED (not in param_names)
2026-08-24 11:10:12 - Pipeline - INFO - SOURCE Source0 : param dec -> FIXED (not in param_names)
2026-08-24 11:10:12 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 11:10:12 - Pipeline - INFO - SOURCE Source0 : param K -> free=True
2026-08-24 11:10:12 - Pipeline - INFO - SOURCE Source0 : param piv -> FIXED (not in param_names)
2026-08-24 11:10:12 - Pipeline - INFO - SOURCE Source0 : param index -> free=True
2026-08-24 11:10:12 - Pipeline - INFO - SOURCE Source0 : param xc -> free=True
2026-08-24 11:10:12 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source1-Spectrum-Log_parabola/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source1-Spectrum-Log_parabola  with compute_err=False, compute_TS=False, make_maps=False
2026-08-24 11:10:13 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 11:10:13 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 11:10:13 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source1-Spectrum-Log_parabola/curModel.model
2026-08-24 11:10:13 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 11:10:13 - Pipeline - INFO - ROI center: 83, 22
2026-08-24 11:10:13 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

['Source0', 'Source1']
83 22 15
Center of ROI  RA: 83.0000 Dec: 22.0000 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source0          83.6336    22.0119   0.588 degrees
Source1          85.7157    23.4480   2.893 degrees

2026-08-24 11:10:27 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  199639.18924471323
TOTAL =  199639.19
CURRENT =  199639.18924471323
CURRENT =  199639.19

Best fit values:

,result,unit
parameter,,
Source0.spectrum.main.Cutoff_powerlaw.K,(6.746685973753895 +/- 0) x 10^-21,1 / (keV s cm2)
Source0.spectrum.main.Cutoff_powerlaw.index,-2.391558361729115 +/- 0,
Source0.spectrum.main.Cutoff_powerlaw.xc,(2.6805616788182003 +/- 0) x 10^10,keV
Source1.Gaussian_on_sphere.sigma,1.033880561670043 +/- 0,deg
Source1.spectrum.main.Log_parabola.K,(4.508855394126594 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Log_parabola.alpha,-2.141123691719451 +/- 0,
Source1.spectrum.main.Log_parabola.beta,(1.5345986391341881 +/- 0) x 10^-3,

Correlation matrix:

nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      199639.189245
total     199639.189245

Values of statistical measures:

     statistical measures
AIC         399292.378543
BIC         399380.289306

Best fit values:

,result,unit
parameter,,
Source0.spectrum.main.Cutoff_powerlaw.K,(6.746685973753895 +/- 0) x 10^-21,1 / (keV s cm2)
Source0.spectrum.main.Cutoff_powerlaw.index,-2.391558361729115 +/- 0,
Source0.spectrum.main.Cutoff_powerlaw.xc,(2.6805616788182003 +/- 0) x 10^10,keV
Source1.Gaussian_on_sphere.sigma,1.033880561670043 +/- 0,deg
Source1.spectrum.main.Log_parabola.K,(4.508855394126594 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Log_parabola.alpha,-2.141123691719451 +/- 0,
Source1.spectrum.main.Log_parabola.beta,(1.5345986391341881 +/- 0) x 10^-3,

Correlation matrix:

nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan
nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      199639.189245
total     199639.189245

Values of statistical measures:

     statistical measures
AIC         399292.378543
BIC         399380.289306

2026-08-24 11:10:53 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source1-Spectrum-Log_parabola/likelihoodResults.fits
2026-08-24 11:10:53 - Pipeline - INFO - Fit Step3-Source1-Spectrum-Log_parabola: -logL=199639.189, AIC=399292.379 (0.67 min)
2026-08-24 11:10:53 - Pipeline - INFO - Spectrum test Source1 -> Log_parabola: delta_TS=-0.00 (threshold 16)
2026-08-24 11:10:53 - Pipeline - INFO - Rejected alternate spectral model Log_parabola for Source1; skipping TS computation
11:08:35 WARNING   The naima package is not available. Models    ]8;id=10518026;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=10518027;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
11:08:35 WARNING   The naima package is not available. Models    ]8;id=1942418;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=1942419;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
11:08:35 WARNING   The naima package is not available. Models    ]8;id=9892765;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=9892766;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
11:08:35 WARNING   The naima package is not available. Models    ]8;id=8906836;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=8906837;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=10518033;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=10518034;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=1942425;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=1942426;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=8906843;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=8906844;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=9892772;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=9892773;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
11:08:36 WARNING   The ebltable package is not available.       ]8;id=1942433;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=1942434;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
11:08:36 WARNING   The ebltable package is not available.       ]8;id=8906851;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=8906852;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
11:08:36 WARNING   The ebltable package is not available.       ]8;id=10518041;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=10518042;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
11:08:36 WARNING   The ebltable package is not available.       ]8;id=9892780;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=9892781;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
11:08:36 INFO      Starting 3ML!                                  ]8;id=10518049;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=10518050;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
11:08:36 INFO      Starting 3ML!                                  ]8;id=8906859;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8906860;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
11:08:36 INFO      Starting 3ML!                                  ]8;id=1942441;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1942442;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
11:08:36 INFO      Starting 3ML!                                  ]8;id=9892788;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9892789;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=8906866;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8906867;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=1942448;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1942449;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=10518056;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=10518057;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=9892795;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9892796;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   but are inform you about optional packages     ]8;id=8906873;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8906874;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=1942455;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1942456;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=10518063;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=10518064;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=9892802;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9892803;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING    to disable these messages, turn off           ]8;id=8906880;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8906881;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=1942462;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1942463;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=10518070;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=10518071;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=9892809;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9892810;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING   no display variable set. using backend for     ]8;id=8906887;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8906888;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=1942469;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1942470;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=10518077;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=10518078;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=9892816;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9892817;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
In file included from In file included from input_line_36In file included from :input_line_361input_line_36:
:In file included from 1/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h:
:In file included from 1/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h:
:In file included from 26:/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h26::
26In file included from :
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.hIn file included from :/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h92::
92:
:
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.hIn file included from :/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h8::929:
:/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h::88::99warning: : 'Py_single_input' macro redefined [-Wmacro-redefined]warning:
:'Py_single_input' macro redefined [-Wmacro-redefined]
warning: 'Py_single_input' macro redefined [-Wmacro-redefined]
###ddeeffiidnefinne Pye_es iP nPgyl_es_iyn_gslienignlpeu__ti n2p5ui6n
p        ^u
t 256
t:        ^ 49
2:5566:
         ^note:
previous definition is here
:49:56: note: previous definition is heret:e49m:p56l
: note: previous definition is here
ate <cltaesmsp lTt>e m[p[altaet e<n o<dcilcalsass sT >Ts >c[ a[[rndo]d]i [sncoadricdso]c]a rcnosntsetdxe]px]rp  rcT o*Tn *l alusatuenxdpnedre(rTr*  Tp*)(  Tn*o epxl)ca eunpote;x c n d/e/r e(pTt*;  Cp +) + /1n/7 ,C +n+ooedxicse1cp7t,;  naorddi sscian c e/ /C +C++r2+d01
7s                                                       ^,i
nce  nodiCs+c+a2r0d
                                                        ^s
ince C++20
                                                       ^
         WARNING   Multinest minimizer not available        ]8;id=9892824;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=9892825;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=1942477;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=1942478;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=10518085;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=10518086;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   PyGMO is not available                   ]8;id=10518092;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=10518093;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=9892831;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=9892832;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=1942484;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=1942485;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
11:08:37 WARNING   Could not import plugin FermiLATLike.py. Do   ]8;id=9892838;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9892839;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#126\126]8;;\
                  you have the relative instrument software
                  installed and configured?
11:08:37 WARNING   Could not import plugin FermiLATLike.py. Do   ]8;id=10518099;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=10518100;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#126\126]8;;\
                  you have the relative instrument software
                  installed and configured?
11:08:37 WARNING   Could not import plugin FermiLATLike.py. Do   ]8;id=1942491;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1942492;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#126\126]8;;\
                  you have the relative instrument software
                  installed and configured?

In [59]:
# result = fit_output 

%load_ext autoreload
%autoreload 2
import importlib
import model_generator
import source_fitter
importlib.reload(source_fitter)
importlib.reload(model_generator)
logger.info('Starting extension fit')


# if config.get('fitting.run_spectrum_test', True):
#     result_ext = source_fitter.run_spectrum_test(result_ext, config, logger, directory_manager)

if config.get('fitting.run_final_refit', True):
    final_result = source_fitter.run_final_refit(result_spectrum_test, config, logger, directory_manager)

2026-08-24 11:19:57 - Pipeline - INFO - Starting extension fit
2026-08-24 11:19:57 - Pipeline - INFO - SOURCE Source0 : param ra -> free=True
2026-08-24 11:19:57 - Pipeline - INFO - SOURCE Source0 : param dec -> free=True
2026-08-24 11:19:57 - Pipeline - INFO - SOURCE Source1 : param lon0 -> free=True
2026-08-24 11:19:57 - Pipeline - INFO - SOURCE Source1 : param lat0 -> free=True
2026-08-24 11:19:57 - Pipeline - INFO - SOURCE Source1 : param sigma -> free=True
2026-08-24 11:19:57 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 11:19:57 - Pipeline - INFO - SOURCE Source0 : param K -> free=True
2026-08-24 11:19:57 - Pipeline - INFO - SOURCE Source0 : param piv -> FIXED (not in param_names)
2026-08-24 11:19:57 - Pipeline - INFO - SOURCE Source0 : param index -> free=True
2026-08-24 11:19:57 - Pipeline - INFO - SOURCE Source0 : param xc -> free=True
2026-08-24 11:19:57 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 11:19:57 - Pipeline - INFO - SOURCE Source1 : param K -> free=True
2026-08-24 11:19:57 - Pipeline - INFO - SOURCE Source1 : param piv -> FIXED (not in param_names)
2026-08-24 11:19:57 - Pipeline - INFO - SOURCE Source1 : param index -> free=True
2026-08-24 11:19:57 - Pipeline - INFO - Skipping background source 'HAWC_bkg_renorm (Parameter)'
2026-08-24 11:19:57 - Pipeline - INFO - Running final joint refit with all parameters free
2026-08-24 11:19:57 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit  with compute_err=False, compute_TS=True, make_maps=True
2026-08-24 11:19:57 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 11:19:57 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 11:19:57 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/curModel.model
2026-08-24 11:19:57 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 11:19:57 - Pipeline - INFO - ROI center: 83, 22
2026-08-24 11:19:57 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
['Source0', 'Source1']
83 22 15
Center of ROI  RA: 83.0000 Dec: 22.0000 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source0          83.6336    22.0119   0.588 degrees
Source1          85.7157    23.4480   2.893 degrees

2026-08-24 11:20:11 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  199637.47717685247
TOTAL =  199637.48
CURRENT =  199637.47717685247
CURRENT =  199637.48

Best fit values:

,result,unit
parameter,,
Source1.Gaussian_on_sphere.lon0,(8.559405204558063 +/- 0) x 10,deg
Source1.Gaussian_on_sphere.lat0,(2.3283621937963117 +/- 0) x 10,deg
Source1.Gaussian_on_sphere.sigma,1.0035421172954992 +/- 0,deg
Source1.spectrum.main.Powerlaw.K,(1.428548988313547 +/- 0) x 10^-23,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.169583189911348 +/- 0,
Source0.position.ra,(8.363354651238323 +/- 0) x 10,deg
Source0.position.dec,(2.201180208382451 +/- 0) x 10,deg
Source0.spectrum.main.Cutoff_powerlaw.K,(6.745300973832867 +/- 0) x 10^-21,1 / (keV s cm2)
Source0.spectrum.main.Cutoff_powerlaw.index,-2.3912802352902895 +/- 0,
Source0.spectrum.main.Cutoff_powerlaw.xc,(2.6784414731128834 +/- 0) x 10^10,keV

Correlation matrix:

nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      199637.477177
total     199637.477177

Values of statistical measures:

     statistical measures
AIC         399294.954458
BIC         399420.541235

Best fit values:

,result,unit
parameter,,
Source1.Gaussian_on_sphere.lon0,(8.559405204558063 +/- 0) x 10,deg
Source1.Gaussian_on_sphere.lat0,(2.3283621937963117 +/- 0) x 10,deg
Source1.Gaussian_on_sphere.sigma,1.0035421172954992 +/- 0,deg
Source1.spectrum.main.Powerlaw.K,(1.428548988313547 +/- 0) x 10^-23,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.169583189911348 +/- 0,
Source0.position.ra,(8.363354651238323 +/- 0) x 10,deg
Source0.position.dec,(2.201180208382451 +/- 0) x 10,deg
Source0.spectrum.main.Cutoff_powerlaw.K,(6.745300973832867 +/- 0) x 10^-21,1 / (keV s cm2)
Source0.spectrum.main.Cutoff_powerlaw.index,-2.3912802352902895 +/- 0,
Source0.spectrum.main.Cutoff_powerlaw.xc,(2.6784414731128834 +/- 0) x 10^10,keV

Correlation matrix:

nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      199637.477177
total     199637.477177

Values of statistical measures:

     statistical measures
AIC         399294.954458
BIC         399420.541235

2026-08-24 11:20:24 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/likelihoodResults.fits
2026-08-24 11:20:24 - Pipeline - INFO - Calculating TS for all sources in the model
2026-08-24 11:20:24 - Pipeline - INFO - Computing TS for source: Source0
2026-08-24 11:20:31 - Pipeline - INFO - TS for source Source0: 87776.40378957643
2026-08-24 11:20:31 - Pipeline - INFO - Computing TS for source: Source1

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  243525.67907164068
TOTAL =  243525.68
CURRENT =  243525.67907164068
CURRENT =  243525.68

2026-08-24 11:20:36 - Pipeline - INFO - TS for source Source1: 233.12927329039667
2026-08-24 11:20:36 - Pipeline - INFO - Saving HAL output maps
2026-08-24 11:20:36 - Pipeline - INFO - SAVE A BIG MAP

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  199754.04181349766
TOTAL =  199754.04
CURRENT =  199754.04181349766
CURRENT =  199754.04

2026-08-24 11:20:59 - Pipeline - INFO - Writing model map...
2026-08-24 11:21:00 - Pipeline - INFO - Fit Step4-FinalRefit: -logL=199637.477, AIC=399294.954 (1.05 min)
2026-08-24 11:21:00 - Pipeline - INFO - Converting HDF5 to FITS: residual_fit.hd5
2026-08-24 11:21:05 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB2C0.fits.gz
2026-08-24 11:21:10 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB3C0.fits.gz
2026-08-24 11:21:14 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB4C0.fits.gz
2026-08-24 11:21:19 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB5C0.fits.gz
2026-08-24 11:21:22 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB6C0.fits.gz
2026-08-24 11:21:25 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB7C0.fits.gz
2026-08-24 11:21:28 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB8C0.fits.gz
2026-08-24 11:21:30 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB9C0.fits.gz
2026-08-24 11:21:32 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB10C0.fits.gz
2026-08-24 11:21:32 - Pipeline - INFO - Successfully converted 9 energy bins to FITS
2026-08-24 11:21:32 - Pipeline - INFO - Output FITS file /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual.fits already exists, skipping map generation

Created FITS files: [PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB2C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB3C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB4C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB5C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB6C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB7C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB8C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB9C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual_binB10C0.fits.gz')]
Path: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit
ROI center in Celestial Coordintes = None, None
Loading Celestial Map

2026-08-24 11:21:33 - Pipeline - INFO - No hotspots found in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fits/residual.fits. Max value: nan
2026-08-24 11:21:33 - Pipeline - INFO - Max value in residual map: nan
2026-08-24 11:21:33 - Pipeline - INFO - Wrote fit summary: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fit_summary.json
2026-08-24 11:21:33 - Pipeline - INFO - Wrote fit summary CSV: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fit_summary.csv

Fits File loaded
Degrees per pixel: 1.0
Peak intensity pixel location: (np.int64(0), np.int64(0))
Peak intensity sky location: <SkyCoord (ICRS): (ra, dec) in deg
    (nan, nan)>
Peak intensity value: nan
path.parent: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit
Saved figure to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/fitsMap.png

11:20:00 WARNING   The naima package is not available. Models    ]8;id=8010374;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=8010375;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
11:20:00 WARNING   The naima package is not available. Models    ]8;id=1954238;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=1954239;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
11:20:00 WARNING   The naima package is not available. Models    ]8;id=10043270;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=10043271;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
11:20:00 WARNING   The naima package is not available. Models    ]8;id=992080;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=992081;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=992087;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=992088;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=1954245;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=1954246;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=10043277;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=10043278;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=8010381;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=8010382;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The ebltable package is not available.       ]8;id=1954253;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=1954254;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=992095;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=992096;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=10043285;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=10043286;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=8010389;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=8010390;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
11:20:01 INFO      Starting 3ML!                                  ]8;id=1954261;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1954262;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
11:20:01 INFO      Starting 3ML!                                  ]8;id=10043293;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=10043294;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
11:20:01 INFO      Starting 3ML!                                  ]8;id=992103;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=992104;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
11:20:01 INFO      Starting 3ML!                                  ]8;id=8010397;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8010398;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=1954268;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1954269;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=992110;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=992111;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=10043300;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=10043301;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=8010404;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8010405;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   but are inform you about optional packages     ]8;id=1954275;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1954276;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=992117;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=992118;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=10043307;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=10043308;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=8010411;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8010412;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING    to disable these messages, turn off           ]8;id=992124;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=992125;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=10043314;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=10043315;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=1954282;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1954283;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING   no display variable set. using backend for     ]8;id=992131;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=992132;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=10043321;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=10043322;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING    to disable these messages, turn off           ]8;id=8010418;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8010419;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING   no display variable set. using backend for     ]8;id=1954289;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1954290;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=8010425;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8010426;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
In file included from input_line_36:In file included from In file included from input_line_36:input_line_361::
In file included from In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h11:
:
In file included from :/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h26::
In file included from 26In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h:
input_line_36In file included from :/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h1::9292:
:
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h:::
8In file included from :/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h9::26 :
warning: In file included from :'Py_single_input' macro redefined [-Wmacro-redefined]26
:
In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h::928:
:/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h92::
8/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h::#9d:e9 :warning:  'Py_single_input' macro redefined [-Wmacro-redefined]warning: f
'Py_single_input' macro redefined [-Wmacro-redefined]8
:9#:d ewarning: if'Py_single_input' macro redefined [-Wmacro-redefined]nien e# dPeyf_isPi
yn_gnsleie _Piyn_p#ndgeslien_gflienien p_uitn p2uPty _2s5566

i        ^n
g        ^l
eu_ti n2:p5:649
:        ^5649:: 56
note: uprevious definition is heret
 :2 5note: 6:previous definition is here49
:56t
e        ^m
p:l tnote: eprevious definition is herem
pa:lt49aet e< c:l56a:s s<note: cprevious definition is herel
t eTm>apslsa tteem  <[c[lpalsantToe>d s< cTl>a  [[[[nnosoidsicsacdrids]cs]a rcdo]na rTd]>] sctoen xsptr]  Tceoxnps*t elxrp rT *T *al uanudn[d[enerr((TT**  po)d ipn)o ensoceaxxcceerlda]u]p tc;o npstt;e  x p rn dTe/r/( TC**+ +p1)7 ,n  n/o/d ioCe+x+c1e7p,t ;s c a  rlda usn/i/n cCe+d+e1r7 ,C +n(oTd*i +spc)a rnnoodeixsdcc asrid2 sien0c
p                                                       ^t
;n e   Cc+e+ 2/C/+ +C200

                                                       ^                                                       ^+
+17, no
discard since C++20
                                                       ^
         WARNING   Multinest minimizer not available        ]8;id=1954297;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=1954298;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=10043329;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=10043330;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=8010433;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=8010434;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=992139;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=992140;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   PyGMO is not available                   ]8;id=8010440;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=8010441;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=1954304;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=1954305;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=10043336;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=10043337;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=992146;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=992147;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   Could not import plugin FermiLATLike.py. Do   ]8;id=10043343;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=10043344;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#126\126]8;;\
                  you have the relative instrument software
                  installed and configured?

In [62]:
final_result

FitResult(model=Model summary:
==============

                  N
Point sources     1
Extended sources  1
Particle sources  0

Free parameters (10):
--------------------

                                                       value     min_value  \
Source1.Gaussian_on_sphere.lon0                    85.594052     84.715655
Source1.Gaussian_on_sphere.lat0                    23.283622      22.44801
Source1.Gaussian_on_sphere.sigma                    1.003542          0.01
Source1.spectrum.main.Powerlaw.K                         0.0           0.0
Source1.spectrum.main.Powerlaw.index               -2.169583          -3.0
Source0.position.ra                                83.633547     80.631907
Source0.position.dec                               22.011802     19.011117
Source0.spectrum.main.Cutoff_powerlaw.K                  0.0           0.0
Source0...index                                     -2.39128         -10.0
Source0.spectrum.main.Cutoff_powerlaw.xc  26784414731.128834  1000000000.0

                                               max_value            unit
Source1.Gaussian_on_sphere.lon0                86.715655             deg
Source1.Gaussian_on_sphere.lat0                 24.44801             deg
Source1.Gaussian_on_sphere.sigma                     3.0             deg
Source1.spectrum.main.Powerlaw.K                     0.0  keV-1 s-1 cm-2
Source1.spectrum.main.Powerlaw.index                -1.0
Source0.position.ra                            86.631907             deg
Source0.position.dec                           25.011117             deg
Source0.spectrum.main.Cutoff_powerlaw.K              0.0  keV-1 s-1 cm-2
Source0...index                                     10.0
Source0.spectrum.main.Cutoff_powerlaw.xc  200000000000.0             keV

Fixed parameters (3):
(abridged. Use complete=True to see all fixed parameters)


Properties (0):
--------------------

(none)


Linked parameters (0):
----------------------

(none)

Independent variables:
----------------------

(none)

Linked functions (0):
----------------------

(none)
, log_like=199637.47717685247, aic=399294.95445833757, ts={'Source0': 87776.40378957643, 'Source1': 233.12927329039667}, model_map_path=PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/model_fit.hd5'), residual_map_path=PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/residual_fit.hd5'), step_dir=PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit'), fitter=<pipeline_fitmodel.threeMLFit object at 0x3069150a0>)

In [61]:
# %load_ext autoreload
# %autoreload 2
# import importlib
# import model_generator
# import source_fitter
# import pipeline_helpers
# importlib.reload(source_fitter)
# importlib.reload(model_generator)
# importlib.reload(pipeline_helpers)
# source_fitter.check_hotspots(resmap, final_result, config, logger)