In [1]:
from core.config import ConfigManager
from astropy.coordinates import SkyCoord
from pathlib import Path
import os
from core.logger import PipelineLogger
from core.directory_manager import DirectoryManager
from core.hdf5_handler import HDF5Handler
from core.map_tools import MapGenerator

16:31:44 WARNING   The naima package is not available. Models that depend on it will not be         ]8;id=8724725;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=8724726;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  available

         WARNING   The GSL library or the pygsl wrapper cannot be loaded. Models that depend on it  ]8;id=8724732;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=8724733;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  will not be available.

         WARNING   The ebltable package is not available. Models that depend on it will not be     ]8;id=8724740;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=8724741;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  available

16:31:45 INFO      Starting 3ML!                                                                     ]8;id=8724748;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8724749;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\

         WARNING   WARNINGs here are NOT errors                                                      ]8;id=8724755;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8724756;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\

         WARNING   but are inform you about optional packages that can be installed                  ]8;id=8724762;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8724763;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\

         WARNING    to disable these messages, turn off start_warning in your config file            ]8;id=8724769;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8724770;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\

         WARNING   no display variable set. using backend for graphics without display (agg)         ]8;id=8724776;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8724777;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\

In file included from input_line_47:1:
In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h:26:
In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h:92:
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h:8:9: warning: 'Py_single_input' macro redefined [-Wmacro-redefined]
#define Py_single_input 256
        ^
:49:56: note: previous definition is here
template <class T> [[nodiscard]] constexpr T* launder(T* p) noexcept;   // C++17, nodiscard since C++20
                                                       ^

         WARNING   Multinest minimizer not available                                           ]8;id=8724784;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=8724785;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\

         WARNING   PyGMO is not available                                                      ]8;id=8724791;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=8724792;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\

         WARNING   Could not import plugin FermiLATLike.py. Do you have the relative instrument     ]8;id=8724798;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8724799;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#126\126]8;;\
                  software installed and configured?

         WARNING   No fermitools installed                                              ]8;id=8724806;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/utils/data_builders/fermi/lat_transient_builder.py\lat_transient_builder.py]8;;\:]8;id=8724807;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/utils/data_builders/fermi/lat_transient_builder.py#44\44]8;;\

         WARNING   Env. variable OMP_NUM_THREADS is not set. Please set it to 1 for optimal         ]8;id=8724813;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8724814;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#335\335]8;;\
                  performances in 3ML

         WARNING   Env. variable MKL_NUM_THREADS is not set. Please set it to 1 for optimal         ]8;id=8724819;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8724820;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#335\335]8;;\
                  performances in 3ML

         WARNING   Env. variable NUMEXPR_NUM_THREADS is not set. Please set it to 1 for optimal     ]8;id=8724825;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=8724826;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#335\335]8;;\
                  performances in 3ML

In [2]:
config = ConfigManager('config.yaml')
method = config.get('fitting_procedure')
coordsys = config.get('coordinates.coord_sys', 'equatorial')
output_path = config.get('fitting.output_dir')
output_dir_name = config.get('fitting.fit_name')

# Test logger
logger = PipelineLogger('./logs')
logger.info("Pipeline test")

directory_manager = DirectoryManager(output_path, output_dir_name, logger=logger)
directory_manager.create_structure()

ra = config.get('coordinates.ra')
dec = config.get('coordinates.dec')
if ra is None or dec is None:
    l = config.get('coordinates.l')
    b = config.get('coordinates.b')
    if l is None or b is None:
        raise ValueError("Config must set either (ra, dec) or (l, b) for the ROI center")
    c = SkyCoord(l, b, frame='galactic', unit='deg')
    ra = float(c.icrs.ra.deg)
    dec = float(c.icrs.dec.deg)
    logger.info(f"Converted galactic coordinates (l={l}, b={b}) to equatorial (RA={ra}, Dec={dec})")
    config.set('coordinates.ra', ra)
    config.set('coordinates.dec', dec)


print(f"Fitting method: {method}")
print(f"Coordinate system: {coordsys}")
print(f"RA: {ra}")
print(f"Dec: {dec}")
print(f"Output path: {output_path}")
print(f"Output directory name: {output_dir_name}")

2026-08-21 16:31:46 - Pipeline - INFO - Pipeline logger initialized
2026-08-21 16:31:46 - Pipeline - INFO - Log level: INFO
2026-08-21 16:31:46 - Pipeline - INFO - Pipeline log: logs/pipeline_20260821_163146.log
2026-08-21 16:31:46 - Pipeline - INFO - Full log: logs/full_log_20260821_163146.log
2026-08-21 16:31:46 - Pipeline - INFO - Pipeline test
2026-08-21 16:31:46 - Pipeline - INFO - Initialized DirectoryManager at /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1
2026-08-21 16:31:46 - Pipeline - INFO - Directory structure created at /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1
2026-08-21 16:31:46 - Pipeline - INFO - Converted galactic coordinates (l=12.5, b=0) to equatorial (RA=273.2187758272126, Dec=-18.100800822935284)

Fitting method: Drips
Coordinate system: G
RA: 273.2187758272126
Dec: -18.100800822935284
Output path: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/
Output directory name: Run1

In [3]:
###Drips 
step_dir = directory_manager.get_step_results_dir('Step0-Allpoint-sources')

In [4]:
def _build_significance_map():
        """Build the significance map from count maps if coordinates.create_sig_map."""
        if not config.get('coordinates.create_sig_map', False):
            return None
        sig_map_path_cfe = config.get('coordinates.sig_map_path')
        if sig_map_path_cfe:
            sig_map_path = Path(sig_map_path_cfe)
        else:
            sig_map_path = directory_manager.get_datamap_dir() / "significance_map.fits"
            logger.info(f"Significance map already exists at {sig_map_path}, skipping generation")
            config.set("coordinates.sig_map_path", str(sig_map_path))
        if sig_map_path.exists():
            logger.info(f"Significance map already exists at {sig_map_path}, skipping generation")
            return sig_map_path
        
        # checkpoint.save_step('build_significance_map', 0, 'running', {})
        count_map_dir = config.get('coordinates.count_map_dir')
        image_bins = config.get('coordinates.image_bins')
        detector_response = config.get('coordinates.detector_response')

        fits_mapping = MapGenerator.find_fits_files_by_bins(count_map_dir, image_bins, logger=logger)
        if not fits_mapping:
            checkpoint.save_step('build_significance_map', 0, 'failed', {'error': 'no count-map FITS files found'})
            raise RuntimeError(f"No count-map FITS files found in {count_map_dir} for bins {image_bins}")
        ra = config.get('coordinates.ra')
        dec = config.get('coordinates.dec')
        if ra is None or dec is None:
            l = config.get('coordinates.l')
            b = config.get('coordinates.b')
            skycoord = SkyCoord(l, b, frame='galactic', unit='deg')
            ra = skycoord.icrs.ra.deg
            dec = skycoord.icrs.dec.deg
            logger.info(f"Converted galactic coordinates (l={l}, b={b}) to equatorial (RA={ra}, Dec={dec})")
            config.set('coordinates.ra', ra)
            config.set('coordinates.dec', dec) 
        
        output_path = MapGenerator.create_healpix_map(
            input_fits_files=list(fits_mapping.values()),
            energy_bins=list(fits_mapping.keys()),
            detector_response=detector_response,
            ra_center=float(config.get('coordinates.ra')),
            dec_center=float(config.get('coordinates.dec')),
            roi_x=float(10.0),
            roi_y=float(10.0),
            output_file=str(sig_map_path),
            logger=logger,
            pixi_manifest_path=config.get('alps.pixi_aerie_folder'),
        )

In [5]:
_build_significance_map()

2026-08-21 16:31:54 - Pipeline - INFO - Significance map already exists at /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/DataMapDir/significance_map.fits, skipping generation
2026-08-21 16:31:54 - Pipeline - INFO - Searching for FITS files in /Users/rishi/Documents/Analysis/data/fhitcountmaps/
2026-08-21 16:31:54 - Pipeline - INFO - Looking for bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']
2026-08-21 16:31:54 - Pipeline - INFO - Found 9/9 energy bins
2026-08-21 16:31:54 - Pipeline - INFO - Creating HEALPix map from 9 FITS files
2026-08-21 16:31:54 - Pipeline - INFO - Energy bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']
2026-08-21 16:31:54 - Pipeline - INFO - Executing HealpixSigFluxMap command:
2026-08-21 16:32:42 - Pipeline - INFO - HEALPix map created successfully: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/DataMapDir/significance_map.fits

WARNING: version mismatch between CFITSIO header (v4.006002) and linked library (v4.0602).

WARNING [CommandLineConfigurator.cc, enableFPExceptions:213]: Floating point exceptions will not be enabled on thisarchitecture
INFO [HealpixSigFluxMap.cc, main:205]: Bin B2C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B3C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B4C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B5C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B6C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B7C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B8C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B9C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B10C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:216]: Opening maps...
INFO [HealpixSigFluxMap.cc, main:274]: Processing detector response...
INFO [TF1PointSource.cc, describe:140]:
TF1 Point Source:
  Name:          ps
  R.A. (J2000):  80 deg
  Dec. (J2000):  20 deg
INFO [Func1.h, PrintOut:94]:
Function: [0]*pow(x/[3],-[1])*exp(-x/[2]):
  (Par 0) Norm: 1 +/- 0.5
  (Par 1) Index: 2.6 +/- 0.1
  (Par 2) CutOff: 1.79769e+308 +/- 8.98847e+307
  (Par 3) Pivot: 7 +/- 0
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root

In [13]:
%load_ext autoreload
%autoreload 2
from drips_seeder import DRIPSSeeder
config = ConfigManager('config.yaml')
seeder = DRIPSSeeder(config, logger, directory_manager, step_path=str(step_dir))
drip_model_path = seeder.run()

2026-08-21 16:45:04 - Pipeline - INFO - Using significance map created: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/DataMapDir/significance_map.fits
2026-08-21 16:45:04 - Pipeline - INFO - Using galactic coordinates from config: (l=12.5, b=0.0)
2026-08-21 16:45:04 - Pipeline - INFO - ROI size: 3.0° x 5.0°
2026-08-21 16:45:04 - Pipeline - INFO - Output directory for seeding: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources
2026-08-21 16:45:04 - Pipeline - INFO - Running seed model search in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources
2026-08-21 16:45:04 - Pipeline - INFO - Loading HAWC data from /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/DataMapDir/significance_map.fits

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
ROI center in Galactic Coordintes = 12.5, 0.0
Loading Galactic Map
Fits File loaded
Degrees per pixel: 0.005555555555555556
  Map shape  : 1800 × 1080  |  pixel size: 0.0056°
  Sig range  : [-1637500000000000486439473119232.00, 32.16]
Peak intensity pixel location: (np.int64(905), np.int64(469))
Peak intensity sky location: <SkyCoord (Galactic): (l, b) in deg
    (12.88888912, 0.03333329)>
Peak intensity value: 32.162945592734715
Plotting contours [7, 9, 12, 13, 14, 15]
  Max significance 32.16sigma exceeds threshold 5.0sigma — proceeding with analysis.
  Image softly floored to -5sigma

Processing radius 0.25°:   0%|          | 0/4 [00:00<?, ?it/s]

Number of pixels corresponding to 0.25 smear radius = 45.00
Estimated background RMS: 0.02241251385184868

Processing radius 0.30°:  25%|██▌       | 1/4 [00:05<00:16,  5.47s/it]

Raw blobs — point source: 2, extended: 2
Sources after 5$\sigma$ filtering: 4
Number of pixels corresponding to 0.30 smear radius = 54.00
Estimated background RMS: 0.02475653871140812

Processing radius 0.40°:  50%|█████     | 2/4 [00:10<00:11,  5.50s/it]

Raw blobs — point source: 2, extended: 2
Sources after 5$\sigma$ filtering: 4
Number of pixels corresponding to 0.40 smear radius = 72.00
Estimated background RMS: 0.028236397850800364

Processing radius 0.50°:  75%|███████▌  | 3/4 [00:16<00:05,  5.60s/it]

Raw blobs — point source: 3, extended: 2
Sources after 5$\sigma$ filtering: 5
Number of pixels corresponding to 0.50 smear radius = 90.00
Estimated background RMS: 0.030876227955128004

Raw blobs — point source: 3, extended: 1
Sources after 5$\sigma$ filtering: 4
  PS  after all cuts:    3
  EXT after all cuts:    2
Plotting contours [7, 9, 12, 13, 14, 15]

Intensity Fraction of pixels greater than 5 sigma detection threshold = 100.0%
Larger blob coord = (np.float64(13.550005009693066), np.float64(0.10555446266700562))
  No smaller blobs overlapping larger blob — tagging as EXT
  PS blob at (x=329, y=978, r=27.00 pixels) with sep=0.353° and no overlap — tagging as PS
PS flagged: 1
Intensity Fraction of pixels greater than 5 sigma detection threshold = 83.4%
Larger blob coord = (np.float64(10.78887238810663), np.float64(0.055554009289751204))
  No smaller blobs overlapping larger blob — tagging as EXT
  PS blob at (x=797, y=918, r=27.00 pixels) with sep=0.282° and no overlap but high TS difference (-8.2) — tagging as PS
PS flagged: 0
  Kept   — PS: 2  EXT: 2
  Removed— PS: 1  EXT: 0
  PS dedup: 2 → 2 kept, 0 removed
Final — PS kept: 2  EXT kept: 2
        PS removed: 1  EXT removed: 0
  Kept   — PS: 2  EXT: 2
  Removed— PS: 1  EXT: 0

2026-08-21 16:45:29 - Pipeline - INFO - Found 4 sources, 4 within original ROI
2026-08-21 16:45:29 - Pipeline - INFO - Results saved to: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources/filtered_sources.yaml
2026-08-21 16:45:29 - Pipeline - INFO - Results saved to: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources/filtered_sources.yaml

Converting blob at (x=350.0, y=918.0, r=90.00 pixels) to coord (RA=273.649°, Dec=-17.128°) with radius 0.50°
Converting blob at (x=847.0, y=909.0, r=90.00 pixels) to coord (RA=272.296°, Dec=-19.573°) with radius 0.50°
Converting blob at (x=329.0, y=978.0, r=27.00 pixels) to coord (RA=273.401°, Dec=-16.866°) with radius 0.15°
Converting blob at (x=473.0, y=902.0, r=27.00 pixels) to coord (RA=273.388°, Dec=-17.771°) with radius 0.15°
Plotting contours [7, 9, 12, 13, 14, 15]
Model saved to: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources/curModel.model

In [15]:
%load_ext autoreload
%autoreload 2
import importlib
import source_fitter
import astromodels
importlib.reload(source_fitter)
logger.info('Starting source_fitter (DRIPS-seeded in-process fit)')

fit_output = source_fitter.run_joint_fit(drip_model_path, config, logger, directory_manager)

2026-08-21 16:52:02 - Pipeline - INFO - Starting source_fitter (DRIPS-seeded in-process fit)
2026-08-21 16:52:02 - Pipeline - INFO - Running joint fit on DRIPS seed model (/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources/curModel.model) in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit
2026-08-21 16:52:02 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit  with compute_err=False, compute_TS=True, make_maps=True
2026-08-21 16:52:02 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-21 16:52:02 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-21 16:52:02 - Pipeline - INFO - Converted galactic coordinates (l=12.5, b=0) to equatorial (RA=273.2187758272126, Dec=-18.100800822935284)
2026-08-21 16:52:02 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step0-Allpoint-sources/curModel.model

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

2026-08-21 16:52:02 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-21 16:52:02 - Pipeline - INFO - ROI center: 273.2187758272126, -18.100800822935284
2026-08-21 16:52:02 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

['Source0', 'Source1', 'Source3']
273.2187758272126 -18.100800822935284 15
Center of ROI  RA: 273.2188 Dec: -18.1008 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source0          273.4012    -16.8665   1.247 degrees
Source1          273.3881    -17.7710   0.367 degrees
Source3          272.2959    -19.5733   1.712 degrees

2026-08-21 16:52:16 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190751.07618951992
TOTAL =  190751.08
CURRENT =  190751.07618951992
CURRENT =  190751.08

Best fit values:

,result,unit
parameter,,
URM.Hermes.N,(1.1995649445130634 +/- 0) x 10,1 / sr
Source0.position.ra,(2.7336805280338883 +/- 0) x 10^2,deg
Source0.position.dec,(-1.6927018851151125 +/- 0) x 10,deg
Source0.spectrum.main.Powerlaw.K,(1.876467606386752 +/- 0) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.2920644343965355 +/- 0,
Source1.position.ra,(2.7338299758221107 +/- 0) x 10^2,deg
Source1.position.dec,(-1.7744203808399235 +/- 0) x 10,deg
Source1.spectrum.main.Powerlaw.K,(9.340720659201345 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.451849454521328 +/- 0,
Source3.Gaussian_on_sphere.lon0,(2.7237537782232484 +/- 0) x 10^2,deg
Source3.Gaussian_on_sphere.lat0,(-1.9361318388379143 +/- 0) x 10,deg
Source3.Gaussian_on_sphere.sigma,(1.842488274064035 +/- 0) x 10^-1,deg
Source3.spectrum.main.Powerlaw.K,(1.475483525724279 +/- 0) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Powerlaw.index,-2.421433073164211 +/- 0,

Correlation matrix:

nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC       190751.07619
total      190751.07619

Values of statistical measures:

     statistical measures
AIC         381530.152579
BIC         381705.977381

Best fit values:

,result,unit
parameter,,
URM.Hermes.N,(1.1995649445130634 +/- 0) x 10,1 / sr
Source0.position.ra,(2.7336805280338883 +/- 0) x 10^2,deg
Source0.position.dec,(-1.6927018851151125 +/- 0) x 10,deg
Source0.spectrum.main.Powerlaw.K,(1.876467606386752 +/- 0) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.2920644343965355 +/- 0,
Source1.position.ra,(2.7338299758221107 +/- 0) x 10^2,deg
Source1.position.dec,(-1.7744203808399235 +/- 0) x 10,deg
Source1.spectrum.main.Powerlaw.K,(9.340720659201345 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.451849454521328 +/- 0,
Source3.Gaussian_on_sphere.lon0,(2.7237537782232484 +/- 0) x 10^2,deg
Source3.Gaussian_on_sphere.lat0,(-1.9361318388379143 +/- 0) x 10,deg
Source3.Gaussian_on_sphere.sigma,(1.842488274064035 +/- 0) x 10^-1,deg
Source3.spectrum.main.Powerlaw.K,(1.475483525724279 +/- 0) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Powerlaw.index,-2.421433073164211 +/- 0,

Correlation matrix:

nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC       190751.07619
total      190751.07619

Values of statistical measures:

     statistical measures
AIC         381530.152579
BIC         381705.977381

2026-08-21 16:53:12 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/likelihoodResults.fits
2026-08-21 16:53:12 - Pipeline - INFO - Saving HAL output maps
2026-08-21 16:53:12 - Pipeline - INFO - SAVE A BIG MAP
2026-08-21 16:53:39 - Pipeline - INFO - Writing model map...
2026-08-21 16:53:40 - Pipeline - INFO - Fit Step1-JointFit: -logL=190751.076, AIC=381530.153 (1.64 min)
16:52:05 WARNING   The naima package is not available. Models    ]8;id=4234146;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=4234147;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
16:52:05 WARNING   The naima package is not available. Models    ]8;id=5301507;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=5301508;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
16:52:05 WARNING   The naima package is not available. Models    ]8;id=7646490;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=7646491;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
16:52:05 WARNING   The naima package is not available. Models    ]8;id=11047850;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=11047851;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=4234153;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=4234154;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=5301514;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=5301515;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=11047857;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=11047858;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=7646497;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=7646498;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The ebltable package is not available.       ]8;id=4234161;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=4234162;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=5301522;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=5301523;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=7646505;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=7646506;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=11047865;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=11047866;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
16:52:06 INFO      Starting 3ML!                                  ]8;id=4234169;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=4234170;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
16:52:06 INFO      Starting 3ML!                                  ]8;id=5301530;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5301531;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
16:52:06 INFO      Starting 3ML!                                  ]8;id=7646513;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=7646514;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
16:52:06 INFO      Starting 3ML!                                  ]8;id=11047873;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=11047874;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=4234176;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=4234177;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=5301537;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5301538;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=7646520;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=7646521;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=11047880;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=11047881;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   but are inform you about optional packages     ]8;id=4234183;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=4234184;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=5301544;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5301545;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=7646527;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=7646528;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=11047887;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=11047888;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING    to disable these messages, turn off           ]8;id=5301551;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5301552;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=4234190;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=4234191;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=11047894;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=11047895;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=7646534;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=7646535;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING   no display variable set. using backend for     ]8;id=5301558;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5301559;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=11047901;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=11047902;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=4234197;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=4234198;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=7646541;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=7646542;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
In file included from In file included from input_line_36input_line_36::11:
:
In file included from In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h::2626In file included from :
In file included from input_line_36/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h::
In file included from In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h:input_line_3692::
1:
:In file included from 92/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h:
:/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h26::
8In file included from :/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h9::/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h :warning: 92:
'Py_single_input' macro redefined [-Wmacro-redefined]1/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h8:
In file included from
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h::98:: 9::#26 d:
warning: warning: 'Py_single_input' macro redefined [-Wmacro-redefined]'Py_single_input' macro redefined [-Wmacro-redefined]

eIn file included from f#/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.hid:e92f:
in/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h#ed ePnye_ sfiinngPlye__ei nPpsuitn y2_5s6g
l        ^e
_inipn:g49l:e56_:i:n8p:u tnote:  previous definition is here2
56
9        ^:
 warning: u'Py_single_input' macro redefined [-Wmacro-redefined]tt e2m5:649
:        ^56
:p
 note: previous definition is here:
#ldaetf49e: t<icnle56 ePy_amsspilna:gsl eT_>itnep u t[ [2n 5onote: 6dprevious definition is herei
s<ccalrads
s        ^
T]>] t emplcaot:[49[:n56o:dnes t<e xinote: psprevious definition is herer
 T*c claarsdtleamupnldaetse  T<]>r ([T[*n cpl)a on]ode icsocsasr dT]x]c ecno>nss t[e[pnto;dxipsrc aTr*td ]]   e x/p/c lC+aru noTn*s tdeexrl(+aT1upnrd eTr**( Tl*a upn)d enro(eTx* cp7),  nneop t;o pd)i sncoae r d/ /x cCe+s+i1n7p,t ;n o d c/e/  iCs+c+e1x7c,eCp+t+;  n o 2/0/
dairsdc  sCi+a                                                       ^
n+c1r7,d  es iCnncoed +i+s2c0aCr+d+
2s                                                       ^0i

n                                                       ^c
e C++20
                                                       ^
         WARNING   Multinest minimizer not available        ]8;id=5301566;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=5301567;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=7646549;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=7646550;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=11047909;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=11047910;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=4234205;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=4234206;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   PyGMO is not available                   ]8;id=4234212;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=4234213;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=5301573;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=5301574;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=11047916;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=11047917;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=7646556;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=7646557;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\

In [16]:
def _build_fit_maps(config, logger, directory_manager, path, name, checkpoint=None):
    """Create significance maps."""

    ra = config.get('coordinates.ra')
    dec = config.get('coordinates.dec')
    if ra is None or dec is None:
        l = config.get('coordinates.l')
        b = config.get('coordinates.b')
        skycoord = SkyCoord(l, b, frame='galactic', unit='deg')
        ra = skycoord.icrs.ra.deg
        dec = skycoord.icrs.dec.deg
        logger.info(f"Converted galactic coordinates (l={l}, b={b}) to equatorial (RA={ra}, Dec={dec})")
        config.set('coordinates.ra', ra)
        config.set('coordinates.dec', dec) 
    
    
    created_files = HDF5Handler.convert_hd5_to_fits(
        input_dir=str(path),
        hd5_filename='residual_fit.hd5',
        output_basename='residual',
        logger=logger
    )
    print(f"Created FITS files: {created_files}")
    bins = config.get('fitting.bins')
    detector_response = config.get('coordinates.detector_response')
    print(f"Path: {path}")

    if os.path.exists(str(path / 'fits' / f'{name}.fits')):
        logger.info(f"Output FITS file {path / 'fits' / f'{name}.fits'} already exists, skipping map generation")
        return path / 'fits' / f'{name}.fits' 
    output_path = MapGenerator.create_healpix_map(
        input_fits_files=list(created_files),
        energy_bins=list(bins),
        detector_response=detector_response,
        ra_center=float(config.get('coordinates.ra')),
        dec_center=float(config.get('coordinates.dec')),
        roi_x=float(config.get('coordinates.roi_x', 4.0)*2.5),
        roi_y=float(config.get('coordinates.roi_y', 4.0)*2),
        output_file=str(path / 'fits' / f'{name}.fits'),
        logger=logger,
        pixi_manifest_path=config.get('alps.pixi_aerie_folder'),
    )

    return output_path
# def check_hotspots(residual_map_path):

In [17]:
resmap = _build_fit_maps(config, logger, directory_manager, fit_output.step_dir, 'residual')

2026-08-21 16:53:59 - Pipeline - INFO - Converted galactic coordinates (l=12.5, b=0) to equatorial (RA=273.2187758272126, Dec=-18.100800822935284)
2026-08-21 16:53:59 - Pipeline - INFO - Converting HDF5 to FITS: residual_fit.hd5
2026-08-21 16:54:04 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB2C0.fits.gz
2026-08-21 16:54:09 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB3C0.fits.gz
2026-08-21 16:54:13 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB4C0.fits.gz
2026-08-21 16:54:17 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB5C0.fits.gz
2026-08-21 16:54:20 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB6C0.fits.gz
2026-08-21 16:54:22 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB7C0.fits.gz
2026-08-21 16:54:24 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB8C0.fits.gz
2026-08-21 16:54:26 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB9C0.fits.gz
2026-08-21 16:54:28 - Pipeline - INFO - Created FITS file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB10C0.fits.gz
2026-08-21 16:54:28 - Pipeline - INFO - Successfully converted 9 energy bins to FITS
2026-08-21 16:54:28 - Pipeline - INFO - Creating HEALPix map from 9 FITS files
2026-08-21 16:54:28 - Pipeline - INFO - Energy bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']
2026-08-21 16:54:28 - Pipeline - INFO - Executing HealpixSigFluxMap command:

Created FITS files: [PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB2C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB3C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB4C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB5C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB6C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB7C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB8C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB9C0.fits.gz'), PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual_binB10C0.fits.gz')]
Path: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit

2026-08-21 16:55:00 - Pipeline - INFO - HEALPix map created successfully: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit/fits/residual.fits

WARNING: version mismatch between CFITSIO header (v4.006002) and linked library (v4.0602).

WARNING [CommandLineConfigurator.cc, enableFPExceptions:213]: Floating point exceptions will not be enabled on thisarchitecture
INFO [HealpixSigFluxMap.cc, main:205]: Bin B2C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B3C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B4C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B5C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B6C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B7C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B8C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B9C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:205]: Bin B10C0 maximum padding radius = 2 deg (extension + padding for extended sources)
INFO [HealpixSigFluxMap.cc, main:216]: Opening maps...
INFO [HealpixSigFluxMap.cc, main:274]: Processing detector response...
INFO [TF1PointSource.cc, describe:140]:
TF1 Point Source:
  Name:          ps
  R.A. (J2000):  80 deg
  Dec. (J2000):  20 deg
INFO [Func1.h, PrintOut:94]:
Function: [0]*pow(x/[3],-[1])*exp(-x/[2]):
  (Par 0) Norm: 1 +/- 0.5
  (Par 1) Index: 2.6 +/- 0.1
  (Par 2) CutOff: 1.79769e+308 +/- 8.98847e+307
  (Par 3) Pivot: 7 +/- 0
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval
Info in <ROOT::Math::BrentMethods::MinimStep>: xmin = 1e-08 xmax = 10 npts = 100
Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root
Error in <TF1::GetX>: [0.000000,10.000000] is not a valid interval
Info in <ROOT::Math::BrentMethods::MinimStep>: Grid search failed to find a root in the  interval

In [18]:
from pipeline_helpers import load_hawc_data, find_peak, make_plots
def check_hotspots(path, fit_output, config, logger):
    mapname = path
    l = config.get('coordinates.l')
    b = config.get('coordinates.b')
    x_length = config.get('coordinates.roi_x')
    y_length = config.get('coordinates.roi_y')
    coord_sys = config.get('coordinates.coord_sys')
    array, _, wcs, _, _, pixel_size = load_hawc_data( mapname, l, b, x_length, y_length, coord_sys )
    max_value = find_peak(array, wcs)
    print(f"path.parent: {path.parent.parent}")
    if max_value > 5:
        name = []
        ra = []
        dec = []
        ext = []
        for source in fit_output.model.sources:
            logger.info(f"Source {source}")
            if source == 'URM':
                continue
            try:
                logger.info(f"Source position: RA={fit_output.model[source].position.ra.value}, Dec={fit_output.model[source].position.dec.value}")
                name.append(source)
                ra.append(fit_output.model[source].position.ra.value)
                dec.append(fit_output.model[source].position.dec.value)
                ext.append(0.01)
            except:
                logger.info(f"Source position: RA={fit_output.model[source].spatial_shape.lon0.value}, Dec={fit_output.model[source].spatial_shape.lat0.value}")
                name.append(source)
                ra.append(fit_output.model[source].spatial_shape.lon0.value)
                dec.append(fit_output.model[source].spatial_shape.lat0.value)
                ext.append(fit_output.model[source].spatial_shape.sigma.value)
        df = {'Name': name, 'ra': ra, 'dec': dec, 'ext': ext}
        make_plots(array, wcs, pixel_size, coord_sys, save_dir = str(path.parent), cmap='ult', hotspots=df)
    logger.info(f"Max value in residual map: {max_value}")

In [19]:
check_hotspots(resmap, fit_output, config, logger)

ROI center in Galactic Coordintes = 12.5, 0
Loading Galactic Map

2026-08-21 16:55:26 - Pipeline - INFO - Source Source0
2026-08-21 16:55:26 - Pipeline - INFO - Source position: RA=273.3680528033888, Dec=-16.927018851151125
2026-08-21 16:55:26 - Pipeline - INFO - Source Source1
2026-08-21 16:55:26 - Pipeline - INFO - Source position: RA=273.3829975822111, Dec=-17.744203808399234
2026-08-21 16:55:26 - Pipeline - INFO - Source URM
2026-08-21 16:55:26 - Pipeline - INFO - Source Source3
2026-08-21 16:55:26 - Pipeline - INFO - Source position: RA=272.3753778223248, Dec=-19.361318388379143

Fits File loaded
Degrees per pixel: 0.005555555555555556
Peak intensity pixel location: (np.int64(841), np.int64(943))
Peak intensity sky location: <SkyCoord (Galactic): (l, b) in deg
    (10.25549306, -0.32220719)>
Peak intensity value: 5.090524600944952
path.parent: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step1-JointFit

2026-08-21 16:55:26 - Pipeline - INFO - Max value in residual map: 5.090524600944952

In [20]:
from typing import List
def _as_list(value) -> List[str]:
    if value is None:
        return []
    return value if isinstance(value, list) else [value]

In [21]:
config = ConfigManager('config.yaml')
model = fit_output.model
baseline_log_like = fit_output.log_like
source_names = list(model.sources.keys())
alt_models = _as_list(config.get('fitting.alternate_spatial_models'))
coord_range = config.get('fitting.extended_source_coord_range', 1.0)
logger.info(f"Sources in the model: {source_names}")
logger.info(f"Baseline log-likelihood: {baseline_log_like}")
logger.info(f"Alternate spatial models: {alt_models}")

2026-08-21 16:55:43 - Pipeline - INFO - Sources in the model: ['Source0', 'Source1', 'URM', 'Source3']
2026-08-21 16:55:43 - Pipeline - INFO - Baseline log-likelihood: 190751.07618951992
2026-08-21 16:55:43 - Pipeline - INFO - Alternate spatial models: ['Gaussian_on_sphere']

In [ ]:
# # for sourcename in source_names:
# #     source = model.sources[sourcename]
# #     print(f"Checking source {source.name} for extension test")
# #     if source.name == 'URM':
# #         params = list(source.spatial_shape.parameters.items())
# #         # params = {k: v.value for k, v in params}
# #         print(f"Source {source.name} spatial shape: {params[0][1]}")
# #         params[0][1].free = False
# #         print(f"Source {source.name} spatial shape: {params[0][1].free}")

# for sourcename in source_names:
#     source = model.sources[sourcename]
#     print(f"Checking source {source.name} for extension test")
#     if source.name == 'URM':
#         params = list(source.spectrum.main._children.items())
#         spec_name, spec_func = params[0]
#         for pname, p in spec_func.parameters.items():
#             p.free = False
#         print(f"Source {source.name} spectrum: {spec_func}")
#         # params = {k: v.value for k, v in params}
#         # params[0][1].free = True
#         # print(f"Source {source.name} spatial shape: {params[0][1].free}")

In [86]:
result = fit_output 
%load_ext autoreload
%autoreload 2
import importlib
import model_generator
import source_fitter

importlib.reload(source_fitter)
importlib.reload(model_generator)

alt_models = _as_list(config.get('fitting.alternate_spatial_models'))
if not alt_models:
    logger.info('No fitting.alternate_spatial_models configured; skipping extension test')

free_dbe = config.get('fitting.free_diffuse_norm', False)
threshold = config.get('likelihood_thresholds.extension_test', 16)
coord_range = config.get('fitting.extended_source_coord_range', 1.0)
runner = FitRunner(
    config_path=str(config.config_file),
    logger=logger,
    roi_template=config.get('roi.roi_template_path'),
)

model = fit_result.model
baseline_log_like = fit_result.log_like
source_names = list(model.sources.keys())
for source_name in source_names:
    if source_name == 'URM':
        logger.info(f'Skipping extension test for {source_name} (URM source)')
        continue
    other_sources = [n for n in model.sources.keys() if n != source_name]
    best_log_like = baseline_log_like
    best_model = model

    for alt_shape in alt_models:
        trial_model = model_generator.ModelGenerator.swap_spatial_shape(
            model, source_name, alt_shape, coord_range=coord_range, logger=logger,
        )
        model_generator.ModelGenerator.set_free(trial_model, other_sources, kind='spatial', free=False, free_diffuse=free_dbe, logger=logger)
        model_generator.ModelGenerator.set_free(trial_model, other_sources, kind='spectral', free=True, free_diffuse=free_dbe, logger=logger)

        step_name = f'Step2-{source_name}-Extension-{alt_shape}'
        step_dir = directory_manager.get_step_results_dir(step_name)
        model_file = model_generator.ModelGenerator.write_model_from_live(
            trial_model, str(directory_manager.get_model_file_path(step_name)), logger=logger,
        )
        trial_model.save("{1}/{0}.yml".format('curModel', step_dir), overwrite=True)
        model_generator.ModelGenerator.write_model_file_from_yaml("{1}/{0}.yml".format('curModel', step_dir), "{1}/{0}.model".format('curModel', step_dir), logger=logger)

        trial_result = runner.fit(
            model_file=str(model_file),
            step_dir=str(step_dir),
            compute_err=config.get('error_and_TS.error_extension', True),
            make_maps=False,
        )

        # logger.info(trial_model)
        # ModelGenerator.set_free(trial_model, other_sources, kind='spatial', free=False)
        # ModelGenerator.set_free(trial_model, other_sources, kind='spectral', free=False)

        # step_name = f'Step2-{source_name}-Extension-{alt_shape}'
        # step_dir = directory_manager.get_step_results_dir(step_name)
        # model_file = ModelGenerator.write_model_from_live(
        #     trial_model, str(directory_manager.get_model_file_path(step_name)), logger=logger,
        # )

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

NameError: name 'FitRunner' is not defined

In [87]:
result = fit_output 

%load_ext autoreload
%autoreload 2
import importlib
import model_generator
import source_fitter
importlib.reload(source_fitter)
importlib.reload(model_generator)
logger.info('Starting extension fit')


if config.get('fitting.run_extension_test', True):
    result_ext = source_fitter.run_extension_test(result, config, logger, directory_manager)

2026-08-24 03:29:50 - Pipeline - INFO - Starting extension fit
2026-08-24 03:29:50 - Pipeline - INFO - Diffuse background normalization status during spectrum test: True
2026-08-24 03:29:50 - Pipeline - INFO - Current best log-likelihood: 190751.076
2026-08-24 03:29:50 - Pipeline - INFO - Spatial shape of source Point_Source, Alternate model Gaussian_on_sphere

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

2026-08-24 03:29:52 - Pipeline - INFO - SOURCE Source1 : param ra -> FIXED (not in param_names)
2026-08-24 03:29:52 - Pipeline - INFO - SOURCE Source1 : param dec -> FIXED (not in param_names)
2026-08-24 03:29:52 - Pipeline - INFO - SOURCE Source3 : param lon0 -> FIXED (not in param_names)
2026-08-24 03:29:52 - Pipeline - INFO - SOURCE Source3 : param lat0 -> FIXED (not in param_names)
2026-08-24 03:29:52 - Pipeline - INFO - SOURCE Source3 : param sigma -> free=True
2026-08-24 03:29:52 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:29:52 - Pipeline - INFO - SOURCE Source1 : param K -> free=True
2026-08-24 03:29:52 - Pipeline - INFO - SOURCE Source1 : param piv -> FIXED (not in param_names)
2026-08-24 03:29:52 - Pipeline - INFO - SOURCE Source1 : param index -> free=True
2026-08-24 03:29:52 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:29:52 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:29:52 - Pipeline - INFO - SOURCE Source3 : param K -> free=True
2026-08-24 03:29:52 - Pipeline - INFO - SOURCE Source3 : param piv -> FIXED (not in param_names)
2026-08-24 03:29:52 - Pipeline - INFO - SOURCE Source3 : param index -> free=True
2026-08-24 03:29:55 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source0-Extension-Gaussian_on_sphere/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source0-Extension-Gaussian_on_sphere  with compute_err=False, compute_TS=True, make_maps=True
2026-08-24 03:29:55 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 03:29:55 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 03:29:55 - Pipeline - INFO - Converted galactic coordinates (l=12.5, b=0) to equatorial (RA=273.2187758272126, Dec=-18.100800822935284)
2026-08-24 03:29:55 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source0-Extension-Gaussian_on_sphere/curModel.model
2026-08-24 03:29:55 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 03:29:55 - Pipeline - INFO - ROI center: 273.2187758272126, -18.100800822935284
2026-08-24 03:29:55 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

['Source1', 'Source3', 'Source0']
273.2187758272126 -18.100800822935284 15
Center of ROI  RA: 273.2188 Dec: -18.1008 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source1          273.3830    -17.7442   0.389 degrees
Source3          272.3754    -19.3613   1.492 degrees
Source0          273.3681    -16.9270   1.182 degrees

2026-08-24 03:30:08 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190716.56751739414
TOTAL =  190716.57
CURRENT =  190716.56751739414
CURRENT =  190716.57

Best fit values:

,result,unit
parameter,,
Source1.spectrum.main.Powerlaw.K,(9.227640596015625 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.4617781943851345 +/- 0,
URM.Hermes.N,(1.054330224069695 +/- 0) x 10,1 / sr
Source3.Gaussian_on_sphere.sigma,(1.8877956540081278 +/- 0) x 10^-1,deg
Source3.spectrum.main.Powerlaw.K,(1.542301918515475 +/- 0) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Powerlaw.index,-2.430522714329224 +/- 0,
Source0.Gaussian_on_sphere.sigma,(3.830753138935077 +/- 0) x 10^-1,deg
Source0.spectrum.main.Powerlaw.K,(5.583157253418873 +/- 0) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.2568013159347324 +/- 0,

Correlation matrix:

nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      190716.567517
total     190716.567517

Values of statistical measures:

     statistical measures
AIC         381451.135120
BIC         381564.165393

Best fit values:

,result,unit
parameter,,
Source1.spectrum.main.Powerlaw.K,(9.227640596015625 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.4617781943851345 +/- 0,
URM.Hermes.N,(1.054330224069695 +/- 0) x 10,1 / sr
Source3.Gaussian_on_sphere.sigma,(1.8877956540081278 +/- 0) x 10^-1,deg
Source3.spectrum.main.Powerlaw.K,(1.542301918515475 +/- 0) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Powerlaw.index,-2.430522714329224 +/- 0,
Source0.Gaussian_on_sphere.sigma,(3.830753138935077 +/- 0) x 10^-1,deg
Source0.spectrum.main.Powerlaw.K,(5.583157253418873 +/- 0) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.2568013159347324 +/- 0,

Correlation matrix:

nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      190716.567517
total     190716.567517

Values of statistical measures:

     statistical measures
AIC         381451.135120
BIC         381564.165393

2026-08-24 03:30:26 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source0-Extension-Gaussian_on_sphere/likelihoodResults.fits
2026-08-24 03:30:26 - Pipeline - INFO - Calculating TS for all sources in the model
2026-08-24 03:30:26 - Pipeline - INFO - Computing TS for source: Source1

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190950.18230089464
TOTAL =  190950.18
CURRENT =  190950.18230089464
CURRENT =  190950.18

2026-08-24 03:30:40 - Pipeline - INFO - TS for source Source1: 467.22956700099166
2026-08-24 03:30:40 - Pipeline - INFO - Computing TS for source: URM
2026-08-24 03:31:02 - Pipeline - INFO - TS for source URM: -639.9672196622705
2026-08-24 03:31:02 - Pipeline - INFO - Computing TS for source: Source3

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190396.583907563
TOTAL =  190396.58
CURRENT =  190396.583907563
CURRENT =  190396.58
Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  191130.79046197256
TOTAL =  191130.79
CURRENT =  191130.79046197256
CURRENT =  191130.79

2026-08-24 03:31:11 - Pipeline - INFO - TS for source Source3: 828.4458891568356
2026-08-24 03:31:11 - Pipeline - INFO - Computing TS for source: Source0

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190796.70506740696
TOTAL =  190796.71
CURRENT =  190796.70506740696
CURRENT =  190796.71

2026-08-24 03:31:17 - Pipeline - INFO - TS for source Source0: 160.2751000256394
2026-08-24 03:31:17 - Pipeline - INFO - Saving HAL output maps
2026-08-24 03:31:17 - Pipeline - INFO - SAVE A BIG MAP
2026-08-24 03:31:36 - Pipeline - INFO - Writing model map...
2026-08-24 03:31:37 - Pipeline - INFO - Fit Step2-Source0-Extension-Gaussian_on_sphere: -logL=190716.568, AIC=381451.135 (1.70 min)
2026-08-24 03:31:37 - Pipeline - INFO - Extension test Source0 -> Gaussian_on_sphere: delta_TS=69.02 (threshold 16)
2026-08-24 03:31:37 - Pipeline - INFO - Accepted alternate spatial model Gaussian_on_sphere for Source0
2026-08-24 03:31:37 - Pipeline - INFO - Current best log-likelihood: 190716.568
2026-08-24 03:31:37 - Pipeline - INFO - Spatial shape of source Point_Source, Alternate model Gaussian_on_sphere
2026-08-24 03:31:40 - Pipeline - INFO - SOURCE Source3 : param lon0 -> FIXED (not in param_names)
2026-08-24 03:31:40 - Pipeline - INFO - SOURCE Source3 : param lat0 -> FIXED (not in param_names)
2026-08-24 03:31:40 - Pipeline - INFO - SOURCE Source3 : param sigma -> free=True
2026-08-24 03:31:40 - Pipeline - INFO - SOURCE Source0 : param lon0 -> FIXED (not in param_names)
2026-08-24 03:31:40 - Pipeline - INFO - SOURCE Source0 : param lat0 -> FIXED (not in param_names)
2026-08-24 03:31:40 - Pipeline - INFO - SOURCE Source0 : param sigma -> free=True
2026-08-24 03:31:40 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:31:40 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:31:40 - Pipeline - INFO - SOURCE Source3 : param K -> free=True
2026-08-24 03:31:40 - Pipeline - INFO - SOURCE Source3 : param piv -> FIXED (not in param_names)
2026-08-24 03:31:40 - Pipeline - INFO - SOURCE Source3 : param index -> free=True
2026-08-24 03:31:40 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:31:40 - Pipeline - INFO - SOURCE Source0 : param K -> free=True
2026-08-24 03:31:40 - Pipeline - INFO - SOURCE Source0 : param piv -> FIXED (not in param_names)
2026-08-24 03:31:40 - Pipeline - INFO - SOURCE Source0 : param index -> free=True
2026-08-24 03:31:40 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source1-Extension-Gaussian_on_sphere/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source1-Extension-Gaussian_on_sphere  with compute_err=False, compute_TS=True, make_maps=True
2026-08-24 03:31:40 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 03:31:40 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 03:31:40 - Pipeline - INFO - Converted galactic coordinates (l=12.5, b=0) to equatorial (RA=273.2187758272126, Dec=-18.100800822935284)
2026-08-24 03:31:40 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source1-Extension-Gaussian_on_sphere/curModel.model
2026-08-24 03:31:40 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 03:31:40 - Pipeline - INFO - ROI center: 273.2187758272126, -18.100800822935284
2026-08-24 03:31:40 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

['Source3', 'Source0', 'Source1']
273.2187758272126 -18.100800822935284 15
Center of ROI  RA: 273.2188 Dec: -18.1008 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source3          272.3754    -19.3613   1.492 degrees
Source0          273.3681    -16.9270   1.182 degrees
Source1          273.3830    -17.7442   0.389 degrees

2026-08-24 03:31:52 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190714.91707318838
TOTAL =  190714.92
CURRENT =  190714.91707318838
CURRENT =  190714.92

Best fit values:

,result,unit
parameter,,
URM.Hermes.N,(1.04341552655981 +/- 0) x 10,1 / sr
Source3.Gaussian_on_sphere.sigma,(1.8937688228381644 +/- 0) x 10^-1,deg
Source3.spectrum.main.Powerlaw.K,(1.5496497748364162 +/- 0) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Powerlaw.index,-2.431647644573416 +/- 0,
Source0.Gaussian_on_sphere.sigma,(3.7817163276822066 +/- 0) x 10^-1,deg
Source0.spectrum.main.Powerlaw.K,(5.482930155456469 +/- 0) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.2551792605297445 +/- 0,
Source1.Gaussian_on_sphere.sigma,(6.653362683478293 +/- 0) x 10^-2,deg
Source1.spectrum.main.Powerlaw.K,(8.189479650359234 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.4602843052550907 +/- 0,

Correlation matrix:

nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      190714.917073
total     190714.917073

Values of statistical measures:

     statistical measures
AIC         381449.834251
BIC         381575.423433

Best fit values:

,result,unit
parameter,,
URM.Hermes.N,(1.04341552655981 +/- 0) x 10,1 / sr
Source3.Gaussian_on_sphere.sigma,(1.8937688228381644 +/- 0) x 10^-1,deg
Source3.spectrum.main.Powerlaw.K,(1.5496497748364162 +/- 0) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Powerlaw.index,-2.431647644573416 +/- 0,
Source0.Gaussian_on_sphere.sigma,(3.7817163276822066 +/- 0) x 10^-1,deg
Source0.spectrum.main.Powerlaw.K,(5.482930155456469 +/- 0) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.2551792605297445 +/- 0,
Source1.Gaussian_on_sphere.sigma,(6.653362683478293 +/- 0) x 10^-2,deg
Source1.spectrum.main.Powerlaw.K,(8.189479650359234 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.index,-2.4602843052550907 +/- 0,

Correlation matrix:

nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      190714.917073
total     190714.917073

Values of statistical measures:

     statistical measures
AIC         381449.834251
BIC         381575.423433

2026-08-24 03:32:20 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source1-Extension-Gaussian_on_sphere/likelihoodResults.fits
2026-08-24 03:32:20 - Pipeline - INFO - Calculating TS for all sources in the model
2026-08-24 03:32:20 - Pipeline - INFO - Computing TS for source: URM
2026-08-24 03:33:09 - Pipeline - INFO - TS for source URM: -668.467764414323
2026-08-24 03:33:09 - Pipeline - INFO - Computing TS for source: Source3

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190380.68319098122
TOTAL =  190380.68
CURRENT =  190380.68319098122
CURRENT =  190380.68
Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  191130.08730020185
TOTAL =  191130.09
CURRENT =  191130.08730020185
CURRENT =  191130.09

2026-08-24 03:33:23 - Pipeline - INFO - TS for source Source3: 830.3404540269403
2026-08-24 03:33:23 - Pipeline - INFO - Computing TS for source: Source0

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190793.53502000545
TOTAL =  190793.54
CURRENT =  190793.53502000545
CURRENT =  190793.54

2026-08-24 03:33:36 - Pipeline - INFO - TS for source Source0: 157.23589363414794
2026-08-24 03:33:36 - Pipeline - INFO - Computing TS for source: Source1

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190950.18219384353
TOTAL =  190950.18
CURRENT =  190950.18219384353
CURRENT =  190950.18

2026-08-24 03:33:48 - Pipeline - INFO - TS for source Source1: 470.5302413103054
2026-08-24 03:33:48 - Pipeline - INFO - Saving HAL output maps
2026-08-24 03:33:48 - Pipeline - INFO - SAVE A BIG MAP
2026-08-24 03:34:09 - Pipeline - INFO - Writing model map...
2026-08-24 03:34:09 - Pipeline - INFO - Fit Step2-Source1-Extension-Gaussian_on_sphere: -logL=190714.917, AIC=381449.834 (2.49 min)
2026-08-24 03:34:09 - Pipeline - INFO - Extension test Source1 -> Gaussian_on_sphere: delta_TS=3.30 (threshold 16)
2026-08-24 03:34:09 - Pipeline - INFO - Skipping extension test for URM (URM source)
2026-08-24 03:34:09 - Pipeline - INFO - Current best log-likelihood: 190716.568
2026-08-24 03:34:09 - Pipeline - INFO - Source Source3 already has spatial shape Gaussian_on_sphere, skipping swap
03:29:58 WARNING   The naima package is not available. Models    ]8;id=9560387;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=9560388;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
03:29:58 WARNING   The naima package is not available. Models    ]8;id=3377815;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=3377816;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
03:29:58 WARNING   The naima package is not available. Models    ]8;id=15953806;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=15953807;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
03:29:58 WARNING   The naima package is not available. Models    ]8;id=5485425;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=5485426;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=15953813;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=15953814;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=3377822;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=3377823;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=9560394;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=9560395;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=5485432;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=5485433;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The ebltable package is not available.       ]8;id=15953821;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=15953822;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=5485440;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=5485441;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=3377830;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=3377831;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=9560402;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=9560403;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
03:29:59 INFO      Starting 3ML!                                  ]8;id=5485448;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5485449;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
03:29:59 INFO      Starting 3ML!                                  ]8;id=15953829;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=15953830;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
03:29:59 INFO      Starting 3ML!                                  ]8;id=9560410;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9560411;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
03:29:59 INFO      Starting 3ML!                                  ]8;id=3377838;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3377839;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=5485455;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5485456;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=15953836;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=15953837;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=9560417;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9560418;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=3377845;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3377846;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   but are inform you about optional packages     ]8;id=5485462;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5485463;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=15953843;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=15953844;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=9560424;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9560425;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=3377852;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3377853;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING    to disable these messages, turn off           ]8;id=5485469;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5485470;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=15953850;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=15953851;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=9560431;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9560432;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=3377859;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3377860;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING   no display variable set. using backend for     ]8;id=5485476;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5485477;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=15953857;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=15953858;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=9560438;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=9560439;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=3377866;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3377867;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
In file included from input_line_36:1:
In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h:26:
In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h:92:
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h:8:9: warning: 'Py_single_input' macro redefined [-Wmacro-redefined]
In file included from input_line_36:1#:
dIn file included from e/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.hf:i26n:
eIn file included from  /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.hP:y92_:
si/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.hn:g8le_input 256
        ^
:49:56: note: previous definition is here
template <class T> [[:nodiscard]] constexpr T* l9aunder(T* p) noexc:ept;   // C+ +1warning: 7, 'Py_single_input' macro redefined [-Wmacro-redefined]nodiscard since C+
+20
                                                       ^
#define Py_single_inIn file included from puinput_line_36t: 12:
5In file included from 6/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h
:        ^26
:
In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h:92:
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h:8:9: warning: 'Py_single_input' macro redefined [-Wmacro-redefined]
:49:56: #note: previous definition is here
define Py_single_inputte 256
        ^
mpl:49a:56t: enote: previous definition is here
<class tTem>pl at[e [<cnlaossd Ti> s[[cnoadirscdar]d]]]  cocnsotenxpsr tT*e lxaupndrer (TT* *p)  nloeaxcuepnt;d  e /r/ (C+T+1*7,  np) noexcept;   // C++17, nodiscard since C++20
                                                       ^
In file included from input_line_36:1:
In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h:26:
In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h:92:
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h:8:9: warning: 'Py_single_input' macro redefined [-Wmacro-redefined]
#define Py_osidngiles_icnpautr 2d56
        ^s
inc:e49:56: note: previous definition is here
template <cl ass T> [[nodiscard]C] +co+ns2te0xp
r                                                        ^T*
 launder(T* p) noexcept;   // C++17, nodiscard since C++20
                                                       ^
03:30:00 WARNING   Multinest minimizer not available        ]8;id=5485484;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=5485485;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
03:30:00 WARNING   Multinest minimizer not available        ]8;id=3377874;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=3377875;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   PyGMO is not available                   ]8;id=3377881;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=3377882;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=5485491;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=5485492;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
03:30:00 WARNING   Multinest minimizer not available        ]8;id=15953865;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=15953866;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   PyGMO is not available                   ]8;id=15953872;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=15953873;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
03:30:00 WARNING   Multinest minimizer not available        ]8;id=9560446;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=9560447;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\

In [88]:
result_ext

FitResult(model=Model summary:
==============

                  N
Point sources     1
Extended sources  3
Particle sources  0

Free parameters (9):
--------------------

                                          value min_value max_value  \
Source1.spectrum.main.Powerlaw.K            0.0       0.0       0.0
Source1.spectrum.main.Powerlaw.index  -2.461778      -3.0      -1.0
URM.Hermes.N                          10.543302      0.01     100.0
Source3.Gaussian_on_sphere.sigma        0.18878      0.01       2.0
Source3.spectrum.main.Powerlaw.K            0.0       0.0       0.0
Source3.spectrum.main.Powerlaw.index  -2.430523      -3.0      -1.0
Source0.Gaussian_on_sphere.sigma       0.383075      0.01       3.0
Source0.spectrum.main.Powerlaw.K            0.0       0.0       0.0
Source0.spectrum.main.Powerlaw.index  -2.256801      -3.0      -1.0

                                                unit
Source1.spectrum.main.Powerlaw.K      keV-1 s-1 cm-2
Source1.spectrum.main.Powerlaw.index
URM.Hermes.N                                    sr-1
Source3.Gaussian_on_sphere.sigma                 deg
Source3.spectrum.main.Powerlaw.K      keV-1 s-1 cm-2
Source3.spectrum.main.Powerlaw.index
Source0.Gaussian_on_sphere.sigma                 deg
Source0.spectrum.main.Powerlaw.K      keV-1 s-1 cm-2
Source0.spectrum.main.Powerlaw.index

Fixed parameters (15):
(abridged. Use complete=True to see all fixed parameters)


Properties (2):
--------------------

                                                                  value  \
URM.Hermes.fits_file  /Users/rishi/Documents/Analysis/Sources/J1813/...
URM.Hermes.frame                                                   icrs

                                            allowed values
URM.Hermes.fits_file                                   NaN
URM.Hermes.frame      [icrs, galactic, fk5, fk4, fk4_no_e]

Linked parameters (0):
----------------------

(none)

Independent variables:
----------------------

(none)

Linked functions (0):
----------------------

(none)
, log_like=190716.56751739414, aic=381451.13512037613, ts={'Source1': 467.22956700099166, 'URM': -639.9672196622705, 'Source3': 828.4458891568356, 'Source0': 160.2751000256394}, model_map_path=PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source0-Extension-Gaussian_on_sphere/model_fit.hd5'), residual_map_path=PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source0-Extension-Gaussian_on_sphere/residual_fit.hd5'), step_dir=PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step2-Source0-Extension-Gaussian_on_sphere'), fitter=<pipeline_fitmodel.threeMLFit object at 0x15026bc50>)

In [92]:
result = fit_output 

%load_ext autoreload
%autoreload 2
import importlib
import model_generator
import source_fitter
importlib.reload(source_fitter)
importlib.reload(model_generator)
logger.info('Starting extension fit')


if config.get('fitting.run_spectrum_test', True):
    result_ext = source_fitter.run_spectrum_test(result_ext, config, logger, directory_manager)

2026-08-24 03:51:42 - Pipeline - INFO - Starting extension fit
2026-08-24 03:51:42 - Pipeline - INFO - Diffuse background normalization status during spectrum test: True
2026-08-24 03:51:42 - Pipeline - INFO - Swapping Source1 spectral shape from Powerlaw to Cutoff_powerlaw
2026-08-24 03:51:42 - Pipeline - INFO - New spectrum class: dict_keys(['K', 'piv', 'index', 'xc'])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

2026-08-24 03:51:47 - Pipeline - INFO - Swapped Source1 spectral shape -> Cutoff_powerlaw
2026-08-24 03:51:47 - Pipeline - INFO - SOURCE Source3 : param lon0 -> FIXED (not in param_names)
2026-08-24 03:51:47 - Pipeline - INFO - SOURCE Source3 : param lat0 -> FIXED (not in param_names)
2026-08-24 03:51:47 - Pipeline - INFO - SOURCE Source3 : param sigma -> free=True
2026-08-24 03:51:47 - Pipeline - INFO - SOURCE Source0 : param lon0 -> FIXED (not in param_names)
2026-08-24 03:51:47 - Pipeline - INFO - SOURCE Source0 : param lat0 -> FIXED (not in param_names)
2026-08-24 03:51:47 - Pipeline - INFO - SOURCE Source0 : param sigma -> free=True
2026-08-24 03:51:47 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:51:47 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:51:47 - Pipeline - INFO - SOURCE Source3 : param K -> free=True
2026-08-24 03:51:47 - Pipeline - INFO - SOURCE Source3 : param piv -> FIXED (not in param_names)
2026-08-24 03:51:47 - Pipeline - INFO - SOURCE Source3 : param index -> free=True
2026-08-24 03:51:47 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:51:47 - Pipeline - INFO - SOURCE Source0 : param K -> free=True
2026-08-24 03:51:47 - Pipeline - INFO - SOURCE Source0 : param piv -> FIXED (not in param_names)
2026-08-24 03:51:47 - Pipeline - INFO - SOURCE Source0 : param index -> free=True
2026-08-24 03:51:47 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source1-Spectrum-Cutoff_powerlaw/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source1-Spectrum-Cutoff_powerlaw  with compute_err=False, compute_TS=False, make_maps=False
2026-08-24 03:51:47 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 03:51:47 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 03:51:47 - Pipeline - INFO - Converted galactic coordinates (l=12.5, b=0) to equatorial (RA=273.2187758272126, Dec=-18.100800822935284)
2026-08-24 03:51:47 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source1-Spectrum-Cutoff_powerlaw/curModel.model
2026-08-24 03:51:47 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 03:51:47 - Pipeline - INFO - ROI center: 273.2187758272126, -18.100800822935284
2026-08-24 03:51:47 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

['Source1', 'Source3', 'Source0']
273.2187758272126 -18.100800822935284 15
Center of ROI  RA: 273.2188 Dec: -18.1008 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source1          273.3830    -17.7442   0.389 degrees
Source3          272.3754    -19.3613   1.492 degrees
Source0          273.3681    -16.9270   1.182 degrees

2026-08-24 03:52:02 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190690.29980999578
TOTAL =  190690.3
CURRENT =  190690.29980999578
CURRENT =  190690.3

Best fit values:

,result,unit
parameter,,
URM.Hermes.N,(1.0714041764487068 +/- 0) x 10,1 / sr
Source3.Gaussian_on_sphere.sigma,(1.8859727531731636 +/- 0) x 10^-1,deg
Source3.spectrum.main.Powerlaw.K,(1.5435754502572976 +/- 0) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Powerlaw.index,-2.431574967240814 +/- 0,
Source0.Gaussian_on_sphere.sigma,(3.8200153204984693 +/- 0) x 10^-1,deg
Source0.spectrum.main.Powerlaw.K,(5.957923811231873 +/- 0) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.2807095233502634 +/- 0,
Source1.spectrum.main.Cutoff_powerlaw.K,(1.7800681691820137 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Cutoff_powerlaw.index,(-6.130480039052133 +/- 0) x 10^-1,
Source1.spectrum.main.Cutoff_powerlaw.xc,(1.021559801614129 +/- 0) x 10^10,keV

Correlation matrix:

nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC       190690.29981
total      190690.29981

Values of statistical measures:

     statistical measures
AIC         381400.599725
BIC         381526.188907

Best fit values:

,result,unit
parameter,,
URM.Hermes.N,(1.0714041764487068 +/- 0) x 10,1 / sr
Source3.Gaussian_on_sphere.sigma,(1.8859727531731636 +/- 0) x 10^-1,deg
Source3.spectrum.main.Powerlaw.K,(1.5435754502572976 +/- 0) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Powerlaw.index,-2.431574967240814 +/- 0,
Source0.Gaussian_on_sphere.sigma,(3.8200153204984693 +/- 0) x 10^-1,deg
Source0.spectrum.main.Powerlaw.K,(5.957923811231873 +/- 0) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.2807095233502634 +/- 0,
Source1.spectrum.main.Cutoff_powerlaw.K,(1.7800681691820137 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Cutoff_powerlaw.index,(-6.130480039052133 +/- 0) x 10^-1,
Source1.spectrum.main.Cutoff_powerlaw.xc,(1.021559801614129 +/- 0) x 10^10,keV

Correlation matrix:

nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC       190690.29981
total      190690.29981

Values of statistical measures:

     statistical measures
AIC         381400.599725
BIC         381526.188907

2026-08-24 03:52:33 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source1-Spectrum-Cutoff_powerlaw/likelihoodResults.fits
2026-08-24 03:52:33 - Pipeline - INFO - Fit Step3-Source1-Spectrum-Cutoff_powerlaw: -logL=190690.300, AIC=381400.600 (0.77 min)
2026-08-24 03:52:33 - Pipeline - INFO - Spectrum test Source1 -> Cutoff_powerlaw: delta_TS=52.54 (threshold 16)
2026-08-24 03:52:33 - Pipeline - INFO - delta_TS above threshold; computing per-source TS for Step3-Source1-Spectrum-Cutoff_powerlaw
2026-08-24 03:52:33 - Pipeline - INFO - Calculating TS for all sources in the model
2026-08-24 03:52:33 - Pipeline - INFO - Computing TS for source: Source1

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190950.18201155003
TOTAL =  190950.18
CURRENT =  190950.18201155003
CURRENT =  190950.18

2026-08-24 03:52:45 - Pipeline - INFO - TS for source Source1: 519.7644031085074
2026-08-24 03:52:45 - Pipeline - INFO - Computing TS for source: URM
2026-08-24 03:53:16 - Pipeline - INFO - TS for source URM: -623.2936667843605
2026-08-24 03:53:16 - Pipeline - INFO - Computing TS for source: Source3

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190378.6529766036
TOTAL =  190378.65
CURRENT =  190378.6529766036
CURRENT =  190378.65
Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  191103.30853922162
TOTAL =  191103.31
CURRENT =  191103.30853922162
CURRENT =  191103.31

2026-08-24 03:53:29 - Pipeline - INFO - TS for source Source3: 826.017458451679
2026-08-24 03:53:29 - Pipeline - INFO - Computing TS for source: Source0

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190770.57410892908
TOTAL =  190770.57
CURRENT =  190770.57410892908
CURRENT =  190770.57

2026-08-24 03:53:36 - Pipeline - INFO - TS for source Source0: 160.5485978666111
2026-08-24 03:53:36 - Pipeline - INFO - Accepted alternate spectral model Cutoff_powerlaw for Source1
2026-08-24 03:53:36 - Pipeline - INFO - Skipping spectrum test for URM (URM source)
2026-08-24 03:53:36 - Pipeline - INFO - Swapping Source3 spectral shape from Powerlaw to Cutoff_powerlaw
2026-08-24 03:53:36 - Pipeline - INFO - New spectrum class: dict_keys(['K', 'piv', 'index', 'xc'])
2026-08-24 03:53:38 - Pipeline - INFO - Swapped Source3 spectral shape -> Cutoff_powerlaw
2026-08-24 03:53:38 - Pipeline - INFO - SOURCE Source1 : param ra -> FIXED (not in param_names)
2026-08-24 03:53:38 - Pipeline - INFO - SOURCE Source1 : param dec -> FIXED (not in param_names)
2026-08-24 03:53:38 - Pipeline - INFO - SOURCE Source0 : param lon0 -> FIXED (not in param_names)
2026-08-24 03:53:38 - Pipeline - INFO - SOURCE Source0 : param lat0 -> FIXED (not in param_names)
2026-08-24 03:53:38 - Pipeline - INFO - SOURCE Source0 : param sigma -> free=True
2026-08-24 03:53:38 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:53:38 - Pipeline - INFO - SOURCE Source1 : param K -> free=True
2026-08-24 03:53:38 - Pipeline - INFO - SOURCE Source1 : param piv -> FIXED (not in param_names)
2026-08-24 03:53:38 - Pipeline - INFO - SOURCE Source1 : param index -> free=True
2026-08-24 03:53:38 - Pipeline - INFO - SOURCE Source1 : param xc -> FIXED (not in param_names)
2026-08-24 03:53:38 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:53:38 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:53:38 - Pipeline - INFO - SOURCE Source0 : param K -> free=True
2026-08-24 03:53:38 - Pipeline - INFO - SOURCE Source0 : param piv -> FIXED (not in param_names)
2026-08-24 03:53:38 - Pipeline - INFO - SOURCE Source0 : param index -> free=True
2026-08-24 03:53:38 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source3-Spectrum-Cutoff_powerlaw/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source3-Spectrum-Cutoff_powerlaw  with compute_err=False, compute_TS=False, make_maps=False
2026-08-24 03:53:38 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 03:53:38 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 03:53:38 - Pipeline - INFO - Converted galactic coordinates (l=12.5, b=0) to equatorial (RA=273.2187758272126, Dec=-18.100800822935284)
2026-08-24 03:53:38 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source3-Spectrum-Cutoff_powerlaw/curModel.model
2026-08-24 03:53:38 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 03:53:38 - Pipeline - INFO - ROI center: 273.2187758272126, -18.100800822935284
2026-08-24 03:53:38 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

['Source1', 'Source0', 'Source3']
273.2187758272126 -18.100800822935284 15
Center of ROI  RA: 273.2188 Dec: -18.1008 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source1          273.3830    -17.7442   0.389 degrees
Source0          273.3681    -16.9270   1.182 degrees
Source3          272.3754    -19.3613   1.492 degrees

2026-08-24 03:53:53 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190689.30978092985
TOTAL =  190689.31
CURRENT =  190689.30978092985
CURRENT =  190689.31

Best fit values:

,result,unit
parameter,,
Source1.spectrum.main.Cutoff_powerlaw.K,(1.764374149248344 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Cutoff_powerlaw.index,(-6.090262334084994 +/- 0) x 10^-1,
URM.Hermes.N,(1.0718754149176761 +/- 0) x 10,1 / sr
Source0.Gaussian_on_sphere.sigma,(3.823333727296158 +/- 0) x 10^-1,deg
Source0.spectrum.main.Powerlaw.K,(6.021751771222142 +/- 0) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.2843784198388697 +/- 0,
Source3.Gaussian_on_sphere.sigma,(1.9142234199751769 +/- 0) x 10^-1,deg
Source3.spectrum.main.Cutoff_powerlaw.K,(1.3224409301312698 +/- 0) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Cutoff_powerlaw.index,-2.2722744157220665 +/- 0,
Source3.spectrum.main.Cutoff_powerlaw.xc,(1.85331581624896 +/- 0) x 10^11,keV

Correlation matrix:

nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      190689.309781
total     190689.309781

Values of statistical measures:

     statistical measures
AIC         381398.619666
BIC         381524.208849

Best fit values:

,result,unit
parameter,,
Source1.spectrum.main.Cutoff_powerlaw.K,(1.764374149248344 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Cutoff_powerlaw.index,(-6.090262334084994 +/- 0) x 10^-1,
URM.Hermes.N,(1.0718754149176761 +/- 0) x 10,1 / sr
Source0.Gaussian_on_sphere.sigma,(3.823333727296158 +/- 0) x 10^-1,deg
Source0.spectrum.main.Powerlaw.K,(6.021751771222142 +/- 0) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.index,-2.2843784198388697 +/- 0,
Source3.Gaussian_on_sphere.sigma,(1.9142234199751769 +/- 0) x 10^-1,deg
Source3.spectrum.main.Cutoff_powerlaw.K,(1.3224409301312698 +/- 0) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Cutoff_powerlaw.index,-2.2722744157220665 +/- 0,
Source3.spectrum.main.Cutoff_powerlaw.xc,(1.85331581624896 +/- 0) x 10^11,keV

Correlation matrix:

nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      190689.309781
total     190689.309781

Values of statistical measures:

     statistical measures
AIC         381398.619666
BIC         381524.208849

2026-08-24 03:54:33 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source3-Spectrum-Cutoff_powerlaw/likelihoodResults.fits
2026-08-24 03:54:33 - Pipeline - INFO - Fit Step3-Source3-Spectrum-Cutoff_powerlaw: -logL=190689.310, AIC=381398.620 (0.91 min)
2026-08-24 03:54:33 - Pipeline - INFO - Spectrum test Source3 -> Cutoff_powerlaw: delta_TS=1.98 (threshold 16)
2026-08-24 03:54:33 - Pipeline - INFO - Rejected alternate spectral model Cutoff_powerlaw for Source3; skipping TS computation
2026-08-24 03:54:33 - Pipeline - INFO - Swapping Source0 spectral shape from Powerlaw to Cutoff_powerlaw
2026-08-24 03:54:33 - Pipeline - INFO - New spectrum class: dict_keys(['K', 'piv', 'index', 'xc'])
2026-08-24 03:54:36 - Pipeline - INFO - Swapped Source0 spectral shape -> Cutoff_powerlaw
2026-08-24 03:54:36 - Pipeline - INFO - SOURCE Source1 : param ra -> FIXED (not in param_names)
2026-08-24 03:54:36 - Pipeline - INFO - SOURCE Source1 : param dec -> FIXED (not in param_names)
2026-08-24 03:54:36 - Pipeline - INFO - SOURCE Source3 : param lon0 -> FIXED (not in param_names)
2026-08-24 03:54:36 - Pipeline - INFO - SOURCE Source3 : param lat0 -> FIXED (not in param_names)
2026-08-24 03:54:36 - Pipeline - INFO - SOURCE Source3 : param sigma -> free=True
2026-08-24 03:54:36 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:54:36 - Pipeline - INFO - SOURCE Source1 : param K -> free=True
2026-08-24 03:54:36 - Pipeline - INFO - SOURCE Source1 : param piv -> FIXED (not in param_names)
2026-08-24 03:54:36 - Pipeline - INFO - SOURCE Source1 : param index -> free=True
2026-08-24 03:54:36 - Pipeline - INFO - SOURCE Source1 : param xc -> FIXED (not in param_names)
2026-08-24 03:54:36 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:54:36 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 03:54:36 - Pipeline - INFO - SOURCE Source3 : param K -> free=True
2026-08-24 03:54:36 - Pipeline - INFO - SOURCE Source3 : param piv -> FIXED (not in param_names)
2026-08-24 03:54:36 - Pipeline - INFO - SOURCE Source3 : param index -> free=True
2026-08-24 03:54:36 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source0-Spectrum-Cutoff_powerlaw/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source0-Spectrum-Cutoff_powerlaw  with compute_err=False, compute_TS=False, make_maps=False
2026-08-24 03:54:36 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 03:54:36 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 03:54:36 - Pipeline - INFO - Converted galactic coordinates (l=12.5, b=0) to equatorial (RA=273.2187758272126, Dec=-18.100800822935284)
2026-08-24 03:54:36 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source0-Spectrum-Cutoff_powerlaw/curModel.model
2026-08-24 03:54:36 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 03:54:36 - Pipeline - INFO - ROI center: 273.2187758272126, -18.100800822935284
2026-08-24 03:54:36 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

['Source1', 'Source3', 'Source0']
273.2187758272126 -18.100800822935284 15
Center of ROI  RA: 273.2188 Dec: -18.1008 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source1          273.3830    -17.7442   0.389 degrees
Source3          272.3754    -19.3613   1.492 degrees
Source0          273.3681    -16.9270   1.182 degrees

2026-08-24 03:54:51 - Pipeline - INFO - Running MLE without error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190687.84885494903
TOTAL =  190687.85
CURRENT =  190687.84885494903
CURRENT =  190687.85

Best fit values:

,result,unit
parameter,,
Source1.spectrum.main.Cutoff_powerlaw.K,(1.9121046580491547 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Cutoff_powerlaw.index,(-6.503209832526102 +/- 0) x 10^-1,
URM.Hermes.N,(1.0710517079941932 +/- 0) x 10,1 / sr
Source3.Gaussian_on_sphere.sigma,(1.886249400668289 +/- 0) x 10^-1,deg
Source3.spectrum.main.Powerlaw.K,(1.5439495925085216 +/- 0) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Powerlaw.index,-2.4316964190148616 +/- 0,
Source0.Gaussian_on_sphere.sigma,(3.9757172339106925 +/- 0) x 10^-1,deg
Source0.spectrum.main.Cutoff_powerlaw.K,(2.9275109910885124 +/- 0) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Cutoff_powerlaw.index,-1.6610534661869736 +/- 0,
Source0.spectrum.main.Cutoff_powerlaw.xc,(5.031623688941674 +/- 0) x 10^10,keV

Correlation matrix:

nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      190687.848855
total     190687.848855

Values of statistical measures:

     statistical measures
AIC         381395.697815
BIC         381521.286997

Best fit values:

,result,unit
parameter,,
Source1.spectrum.main.Cutoff_powerlaw.K,(1.9121046580491547 +/- 0) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Cutoff_powerlaw.index,(-6.503209832526102 +/- 0) x 10^-1,
URM.Hermes.N,(1.0710517079941932 +/- 0) x 10,1 / sr
Source3.Gaussian_on_sphere.sigma,(1.886249400668289 +/- 0) x 10^-1,deg
Source3.spectrum.main.Powerlaw.K,(1.5439495925085216 +/- 0) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Powerlaw.index,-2.4316964190148616 +/- 0,
Source0.Gaussian_on_sphere.sigma,(3.9757172339106925 +/- 0) x 10^-1,deg
Source0.spectrum.main.Cutoff_powerlaw.K,(2.9275109910885124 +/- 0) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Cutoff_powerlaw.index,-1.6610534661869736 +/- 0,
Source0.spectrum.main.Cutoff_powerlaw.xc,(5.031623688941674 +/- 0) x 10^10,keV

Correlation matrix:

nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      190687.848855
total     190687.848855

Values of statistical measures:

     statistical measures
AIC         381395.697815
BIC         381521.286997

2026-08-24 03:55:30 - Pipeline - INFO - Fit results saved to /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step3-Source0-Spectrum-Cutoff_powerlaw/likelihoodResults.fits
2026-08-24 03:55:30 - Pipeline - INFO - Fit Step3-Source0-Spectrum-Cutoff_powerlaw: -logL=190687.849, AIC=381395.698 (0.89 min)
2026-08-24 03:55:30 - Pipeline - INFO - Spectrum test Source0 -> Cutoff_powerlaw: delta_TS=4.90 (threshold 16)
2026-08-24 03:55:30 - Pipeline - INFO - Rejected alternate spectral model Cutoff_powerlaw for Source0; skipping TS computation
03:51:51 WARNING   The naima package is not available. Models    ]8;id=1302513;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=1302514;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
03:51:51 WARNING   The naima package is not available. Models    ]8;id=5575718;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=5575719;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astr03:51:51 WARNING   The naima package is not available. Models    ]8;id=3762401;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=3762402;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
03:51:51 WARNING   The naima package is not available. Models    ]8;id=5542682;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=5542683;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=3762408;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=3762409;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=1302520;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=1302521;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=5542689;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=5542690;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
omodels/functions/functions_1D/functions.py#43\43]8;;\
                  that depend on it will not be available
         WARNING   The GSL library or the pygsl wrapper cannot   ]8;id=5575725;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=5575726;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  be loaded. Models that depend on it will not
                  be available.
         WARNING   The ebltable package is not available.       ]8;id=3762416;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=3762417;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=5542697;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=5542698;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=1302528;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=1302529;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
         WARNING   The ebltable package is not available.       ]8;id=5575733;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=5575734;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  Models that depend on it will not be
                  available
03:51:52 INFO      Starting 3ML!                                  ]8;id=5575741;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5575742;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
03:51:52 INFO      Starting 3ML!                                  ]8;id=1302536;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1302537;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
03:51:52 INFO      Starting 3ML!                                  ]8;id=3762424;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3762425;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
03:51:52 INFO      Starting 3ML!                                  ]8;id=5542705;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5542706;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#44\44]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=5575748;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5575749;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=3762431;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3762432;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=1302543;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1302544;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   WARNINGs here are NOT errors                   ]8;id=5542712;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5542713;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#45\45]8;;\
         WARNING   but are inform you about optional packages     ]8;id=3762438;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3762439;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=5542719;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5542720;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=5575755;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5575756;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING   but are inform you about optional packages     ]8;id=1302550;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1302551;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#46\46]8;;\
                  that can be installed
         WARNING    to disable these messages, turn off           ]8;id=3762445;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3762446;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=5542726;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5542727;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=5575762;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5575763;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING    to disable these messages, turn off           ]8;id=1302557;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1302558;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#47\47]8;;\
                  start_warning in your config file
         WARNING   no display variable set. using backend for     ]8;id=3762452;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3762453;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=5542733;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5542734;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=1302564;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=1302565;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
         WARNING   no display variable set. using backend for     ]8;id=5575769;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=5575770;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/__init__.py#53\53]8;;\
                  graphics without display (agg)
In file included from input_line_36In file included from :input_line_36In file included from :input_line_361In file included from :
In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h1:26::
In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h1::
26:
input_line_36:In file included from 1:
In file included from In file included from /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h::9292:
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h:
:26In file included from :
:
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/CPyCppyy/API.h/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.hIn file included from :/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h8::/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.h9::8 :warning: 9:'Py_single_input' macro redefined [-Wmacro-redefined]
warning: 'Py_single_input' macro redefined [-Wmacro-redefined]:
26:
92In file included from :
/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/Python.h#de/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.hf:i:892::
9/Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/include/python3.12/compile.hn#:ed8 :P9y::e fwarning: _isnien gPlye'Py_single_input' macro redefined [-Wmacro-redefined]_
in_psuit# d2e5nf iwarning: n6'Py_single_input' macro redefined [-Wmacro-redefined]

        ^
e gPly#ed_eifnipnue_ :Py49s:i56ntg l2e5:6
note:         ^_previous definition is here_
si
nignlpeu_ti n2t5:e649m
p        ^l
p:u56t: a2t5e6  :<49c:l56
note:         ^previous definition is here

: note: previous definition is herea
ss :T49>t e[m[pnloa:dt56i:s ctaermdp]l]a note: cprevious definition is hereo
ntsee  <<cctleatsesm xTp>rp lTa t[e[ *< clnloadsisa uTnsdc>ea rr[([Tnl*oa sps)d ]n]o eT x>c e[cp[otn;sd ti s c/aneoxdpirs c/a rCdT]*+]+ 1c7r,  dnloaduinsdceorn(sTt*e xpp)r  n]T]*  aloauredx cseipntc;n d eer (CT */ /p+ cCo+)n snto+e1x7ce,e+p2t0;
 x                                                       ^
no d pirs cTa/r/d  *C +l+a1s7i,n ucned eCn+o+d2r0(
T                                                       ^*i spc)a
rd s innoceex cCe+p+t2;0
                                                        ^
// C++17, nodiscard since C++20
                                                       ^
         WARNING   Multinest minimizer not available        ]8;id=1302572;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=1302573;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=5542741;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=5542742;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=3762460;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=3762461;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   Multinest minimizer not available        ]8;id=5575777;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=5575778;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\
         WARNING   PyGMO is not available                   ]8;id=1302579;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=1302580;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=5542748;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=5542749;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=3762467;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=3762468;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\
         WARNING   PyGMO is not available                   ]8;id=5575784;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=5575785;file:///Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/minimizer/minimization.py#1228\1228]8;;\

In [ ]:
result = fit_output 

%load_ext autoreload
%autoreload 2
import importlib
import model_generator
import source_fitter
importlib.reload(source_fitter)
importlib.reload(model_generator)
logger.info('Starting extension fit')


# if config.get('fitting.run_spectrum_test', True):
#     result_ext = source_fitter.run_spectrum_test(result_ext, config, logger, directory_manager)

if config.get('fitting.run_final_refit', True):
    result = source_fitter.run_final_refit(result, config, logger, directory_manager)

2026-08-24 09:45:47 - Pipeline - INFO - Starting extension fit
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source0 : param ra -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source0 : param dec -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source1 : param ra -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source1 : param dec -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source3 : param lon0 -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source3 : param lat0 -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source3 : param sigma -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source0 : param K -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source0 : param piv -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source0 : param index -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source1 : param K -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source1 : param piv -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source1 : param index -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 09:45:47 - Pipeline - INFO - TESTING SPECTRAL
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source3 : param K -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source3 : param piv -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - SOURCE Source3 : param index -> free=True
2026-08-24 09:45:47 - Pipeline - INFO - Skipping background source 'HAWC_bkg_renorm (Parameter)'
2026-08-24 09:45:47 - Pipeline - INFO - Running final joint refit with all parameters free
2026-08-24 09:45:47 - Pipeline - INFO - Fitting model /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/curModel.model in /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit  with compute_err=True, compute_TS=True, make_maps=True
2026-08-24 09:45:47 - Pipeline - INFO - Map tree: /Users/rishi/Documents/Analysis/data/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
2026-08-24 09:45:47 - Pipeline - INFO - Detector response: /Users/rishi/Documents/Analysis/data/detRes-fhit2pct-pass5f-mlp-refit.root
2026-08-24 09:45:47 - Pipeline - INFO - Converted galactic coordinates (l=12.5, b=0) to equatorial (RA=273.2187758272126, Dec=-18.100800822935284)
2026-08-24 09:45:47 - Pipeline - INFO - Model file: /Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/curModel.model

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

2026-08-24 09:45:47 - Pipeline - INFO - No ROI template provided, computing ROI from provided ra and dec
2026-08-24 09:45:47 - Pipeline - INFO - ROI center: 273.2187758272126, -18.100800822935284
2026-08-24 09:45:47 - Pipeline - INFO - Running threeML fit pipeline with bins: ['B2C0', 'B3C0', 'B4C0', 'B5C0', 'B6C0', 'B7C0', 'B8C0', 'B9C0', 'B10C0']

['Source0', 'Source1', 'Source3']
273.2187758272126 -18.100800822935284 15
Center of ROI  RA: 273.2188 Dec: -18.1008 Radius: 15.00
Source         RA:          Dec:           Distance to center
Source0          273.3681    -16.9270   1.182 degrees
Source1          273.3830    -17.7442   0.389 degrees
Source3          272.3754    -19.3613   1.492 degrees

2026-08-24 09:46:05 - Pipeline - INFO - Running MLE with error estimation

Added Likelihood correction to: /Users/rishi/Documents/Analysis/aerie/.pixi/envs/threeml/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py
TOTAL =  190751.04808565087
TOTAL =  190751.05
CURRENT =  190751.04808565087
CURRENT =  190751.05

Best fit values:

,result,unit
parameter,,
URM.Hermes.N,(1.20 +/- 0.05) x 10,1 / sr
Source0.position.ra,(2.73368 +/- 0.00021) x 10^2,deg
Source0.position.dec,(-1.6927 +/- 0.0020) x 10,deg
Source0.spectrum.main.Powerlaw.K,(1.9 -0.9 +1.7) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.piv,(2.0 +/- 0.7) x 10^9,keV
Source0.spectrum.main.Powerlaw.index,-2.29 +/- 0.11,
Source1.position.ra,(2.73383 +/- 0.00012) x 10^2,deg
Source1.position.dec,(-1.7744 +/- 0.0016) x 10,deg
Source1.spectrum.main.Powerlaw.K,(9.3 -3.0 +4) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.piv,(2.00 +/- 0.32) x 10^9,keV
Source1.spectrum.main.Powerlaw.index,-2.45 +/- 0.05,
Source3.Gaussian_on_sphere.lon0,(2.72375 +/- 0.00022) x 10^2,deg
Source3.Gaussian_on_sphere.lat0,(-1.9361 +/- 0.0015) x 10,deg
Source3.Gaussian_on_sphere.sigma,(1.84 +/- 0.16) x 10^-1,deg
Source3.spectrum.main.Powerlaw.K,(1.5 -0.7 +1.3) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Powerlaw.piv,(2.00 +/- 0.34) x 10^9,keV
Source3.spectrum.main.Powerlaw.index,-2.42 +/- 0.09,

Correlation matrix:

 1.00  0.04  0.03  0.01 -0.05  0.07 ...  0.03 -0.02 -0.13 -0.14  0.10  0.17
 0.04  1.00  0.15  0.11 -0.10  0.08 ...  0.23  0.07 -0.20 -0.42  0.40  0.39
 0.03  0.15  1.00  0.02 -0.02  0.01 ...  0.06  0.02 -0.05 -0.11  0.10  0.10
 0.01  0.11  0.02  1.00 -0.92  0.30 ...  0.50  0.06 -0.08 -0.28  0.28  0.26
-0.05 -0.10 -0.02 -0.92  1.00 -0.61 ... -0.48 -0.05  0.06  0.23 -0.21 -0.24
 0.07  0.08  0.01  0.30 -0.61  1.00 ...  0.20  0.01  0.01 -0.02 -0.02  0.11
 0.03  0.04  0.01  0.00  0.00 -0.00 ...  0.05  0.02 -0.06 -0.11  0.11  0.10
 0.15  0.32  0.10  0.14 -0.13  0.06 ...  0.42  0.13 -0.38 -0.78  0.74  0.73
-0.14 -0.38 -0.10  0.12 -0.13  0.05 ... -0.23 -0.12  0.37  0.72 -0.68 -0.67
 0.08  0.37  0.09 -0.17  0.18 -0.09 ...  0.18  0.11 -0.36 -0.69  0.66  0.61
 0.13  0.10  0.04  0.27 -0.29  0.19 ...  0.30  0.04 -0.08 -0.21  0.16  0.29
 0.03  0.23  0.06  0.50 -0.48  0.20 ...  1.00  0.14 -0.29 -0.55  0.52  0.53
-0.02  0.07  0.02  0.06 -0.05  0.01 ...  0.14  1.00 -0.22 -0.17  0.14  0.16
-0.13 -0.20 -0.05 -0.08  0.06  0.01 ... -0.29 -0.22  1.00  0.48 -0.40 -0.43
-0.14 -0.42 -0.11 -0.28  0.23 -0.02 ... -0.55 -0.17  0.48  1.00 -0.97 -0.89
 0.10  0.40  0.10  0.28 -0.21 -0.02 ...  0.52  0.14 -0.40 -0.97  1.00  0.77
 0.17  0.39  0.10  0.26 -0.24  0.11 ...  0.53  0.16 -0.43 -0.89  0.77  1.00

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      190751.048086
total     190751.048086

Values of statistical measures:

     statistical measures
AIC         381536.096462
BIC         381749.597959

Best fit values:

,result,unit
parameter,,
URM.Hermes.N,(1.20 +/- 0.05) x 10,1 / sr
Source0.position.ra,(2.73368 +/- 0.00021) x 10^2,deg
Source0.position.dec,(-1.6927 +/- 0.0020) x 10,deg
Source0.spectrum.main.Powerlaw.K,(1.9 -0.9 +1.7) x 10^-22,1 / (keV s cm2)
Source0.spectrum.main.Powerlaw.piv,(2.0 +/- 0.7) x 10^9,keV
Source0.spectrum.main.Powerlaw.index,-2.29 +/- 0.11,
Source1.position.ra,(2.73383 +/- 0.00012) x 10^2,deg
Source1.position.dec,(-1.7744 +/- 0.0016) x 10,deg
Source1.spectrum.main.Powerlaw.K,(9.3 -3.0 +4) x 10^-22,1 / (keV s cm2)
Source1.spectrum.main.Powerlaw.piv,(2.00 +/- 0.32) x 10^9,keV
Source1.spectrum.main.Powerlaw.index,-2.45 +/- 0.05,
Source3.Gaussian_on_sphere.lon0,(2.72375 +/- 0.00022) x 10^2,deg
Source3.Gaussian_on_sphere.lat0,(-1.9361 +/- 0.0015) x 10,deg
Source3.Gaussian_on_sphere.sigma,(1.84 +/- 0.16) x 10^-1,deg
Source3.spectrum.main.Powerlaw.K,(1.5 -0.7 +1.3) x 10^-21,1 / (keV s cm2)
Source3.spectrum.main.Powerlaw.piv,(2.00 +/- 0.34) x 10^9,keV
Source3.spectrum.main.Powerlaw.index,-2.42 +/- 0.09,

Correlation matrix:

 1.00  0.04  0.03  0.01 -0.05  0.07 ...  0.03 -0.02 -0.13 -0.14  0.10  0.17
 0.04  1.00  0.15  0.11 -0.10  0.08 ...  0.23  0.07 -0.20 -0.42  0.40  0.39
 0.03  0.15  1.00  0.02 -0.02  0.01 ...  0.06  0.02 -0.05 -0.11  0.10  0.10
 0.01  0.11  0.02  1.00 -0.92  0.30 ...  0.50  0.06 -0.08 -0.28  0.28  0.26
-0.05 -0.10 -0.02 -0.92  1.00 -0.61 ... -0.48 -0.05  0.06  0.23 -0.21 -0.24
 0.07  0.08  0.01  0.30 -0.61  1.00 ...  0.20  0.01  0.01 -0.02 -0.02  0.11
 0.03  0.04  0.01  0.00  0.00 -0.00 ...  0.05  0.02 -0.06 -0.11  0.11  0.10
 0.15  0.32  0.10  0.14 -0.13  0.06 ...  0.42  0.13 -0.38 -0.78  0.74  0.73
-0.14 -0.38 -0.10  0.12 -0.13  0.05 ... -0.23 -0.12  0.37  0.72 -0.68 -0.67
 0.08  0.37  0.09 -0.17  0.18 -0.09 ...  0.18  0.11 -0.36 -0.69  0.66  0.61
 0.13  0.10  0.04  0.27 -0.29  0.19 ...  0.30  0.04 -0.08 -0.21  0.16  0.29
 0.03  0.23  0.06  0.50 -0.48  0.20 ...  1.00  0.14 -0.29 -0.55  0.52  0.53
-0.02  0.07  0.02  0.06 -0.05  0.01 ...  0.14  1.00 -0.22 -0.17  0.14  0.16
-0.13 -0.20 -0.05 -0.08  0.06  0.01 ... -0.29 -0.22  1.00  0.48 -0.40 -0.43
-0.14 -0.42 -0.11 -0.28  0.23 -0.02 ... -0.55 -0.17  0.48  1.00 -0.97 -0.89
 0.10  0.40  0.10  0.28 -0.21 -0.02 ...  0.52  0.14 -0.40 -0.97  1.00  0.77
 0.17  0.39  0.10  0.26 -0.24  0.11 ...  0.53  0.16 -0.43 -0.89  0.77  1.00

Values of -log(likelihood) at the minimum:

       -log(likelihood)
HAWC      190751.048086
total     190751.048086

Values of statistical measures:

     statistical measures
AIC         381536.096462
BIC         381749.597959

In [99]:
result

FitResult(model=Model summary:
==============

                  N
Point sources     2
Extended sources  2
Particle sources  0

Free parameters (17):
--------------------

                                                  value   min_value  \
URM.Hermes.N                                  12.001382        0.01
Source0.position.ra                          273.368172  270.401179
Source0.position.dec                         -16.927167  -19.866496
Source0.spectrum.main.Powerlaw.K                    0.0         0.0
Source0.spectrum.main.Powerlaw.piv     1997653075.17849        None
Source0.spectrum.main.Powerlaw.index           -2.29438        -3.0
Source1.position.ra                          273.383009  270.388131
Source1.position.dec                         -17.744207  -20.771011
Source1.spectrum.main.Powerlaw.K                    0.0         0.0
Source1.spectrum.main.Powerlaw.piv    1997850224.748411        None
Source1.spectrum.main.Powerlaw.index          -2.450398        -3.0
Source3.Gaussian_on_sphere.lon0              272.375295  269.295918
Source3.Gaussian_on_sphere.lat0               -19.36133  -22.573289
Source3.Gaussian_on_sphere.sigma               0.184417        0.01
Source3.spectrum.main.Powerlaw.K                    0.0         0.0
Source3.spectrum.main.Powerlaw.piv     2000647317.25322        None
Source3.spectrum.main.Powerlaw.index          -2.421776        -3.0

                                       max_value            unit
URM.Hermes.N                               100.0            sr-1
Source0.position.ra                   276.401179             deg
Source0.position.dec                  -13.866496             deg
Source0.spectrum.main.Powerlaw.K             0.0  keV-1 s-1 cm-2
Source0.spectrum.main.Powerlaw.piv          None             keV
Source0.spectrum.main.Powerlaw.index        -1.0
Source1.position.ra                   276.388131             deg
Source1.position.dec                  -14.771011             deg
Source1.spectrum.main.Powerlaw.K             0.0  keV-1 s-1 cm-2
Source1.spectrum.main.Powerlaw.piv          None             keV
Source1.spectrum.main.Powerlaw.index        -1.0
Source3.Gaussian_on_sphere.lon0       275.295918             deg
Source3.Gaussian_on_sphere.lat0       -16.573289             deg
Source3.Gaussian_on_sphere.sigma             2.0             deg
Source3.spectrum.main.Powerlaw.K             0.0  keV-1 s-1 cm-2
Source3.spectrum.main.Powerlaw.piv          None             keV
Source3.spectrum.main.Powerlaw.index        -1.0

Fixed parameters (6):
(abridged. Use complete=True to see all fixed parameters)


Properties (2):
--------------------

                                                                  value  \
URM.Hermes.fits_file  /Users/rishi/Documents/Analysis/Sources/J1813/...
URM.Hermes.frame                                                   icrs

                                            allowed values
URM.Hermes.fits_file                                   NaN
URM.Hermes.frame      [icrs, galactic, fk5, fk4, fk4_no_e]

Linked parameters (0):
----------------------

(none)

Independent variables:
----------------------

(none)

Linked functions (0):
----------------------

(none)
, log_like=190751.04808565087, aic=381536.09646230156, ts={'Source0': 91.27881391526898, 'Source1': 530.4963144836947, 'URM': 712.9706483683549, 'Source3': 808.1390080836136}, model_map_path=PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/model_fit.hd5'), residual_map_path=PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit/residual_fit.hd5'), step_dir=PosixPath('/Users/rishi/Documents/Analysis/Sources/AstroImageDetection-fitmodel/HAWC-ImageProcessing-3MLFit/hawc_analysis/Run1/Results/Step4-FinalRefit'), fitter=<pipeline_fitmodel.threeMLFit object at 0x39ac0eba0>)

In [ ]:
%load_ext autoreload
%autoreload 2
import importlib
import model_generator
import source_fitter
importlib.reload(source_fitter)
importlib.reload(model_generator)

source_fitter.save_fit_summary(result, logger)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

AttributeError: 'FitResult' object has no attribute 'ts'

In [98]:
from model_generator import ModelGenerator
num_sources = len(result.model.sources)
model_path = directory_manager.get_model_file_path('Final')
yml_path = str(model_path).replace('.model', '.yml') if str(model_path).endswith('.model') else f'{model_path}.yml'
result.model.save(yml_path, overwrite=True)
ModelGenerator.write_model_file_from_yaml(yml_path, str(model_path), logger=logger)

2026-08-24 09:27:58 - Pipeline - INFO - Skipping background source 'HAWC_bkg_renorm (Parameter)'